-- MySQL Script generated by MySQL Workbench
-- ter 03 out 2017 21:00:01 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mundo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mundo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mundo` DEFAULT CHARACTER SET utf8 ;
USE `mundo` ;

-- -----------------------------------------------------
-- Table `mundo`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundo`.`pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nomePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundo`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundo`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nomeEstado` VARCHAR(45) NOT NULL,
  `pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_estado_pais_idx` (`pais_idPais` ASC),
  CONSTRAINT `fk_estado_pais`
    FOREIGN KEY (`pais_idPais`)
    REFERENCES `mundo`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mundo`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mundo`.`cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(45) NOT NULL,
  `estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_cidade_estado1_idx` (`estado_idEstado` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `mundo`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
