INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abreu e Lima', 17),
('Afogados da Ingazeira', 17),
('Afranio', 17),
('Agrestina', 17),
('Agua Preta', 17),
('Aguas Belas', 17),
('Alagoinha', 17),
('Alianca', 17),
('Altinho', 17),
('Amaraji', 17),
('Angelim', 17),
('Aracoiaba', 17),
('Araripina', 17),
('Arcoverde', 17),
('Barra de Guabiraba', 17),
('Barreiros', 17),
('Belem de Maria', 17),
('Belem de Sao Francisco', 17),
('Belo Jardim', 17),
('Betania', 17),
('Bezerros', 17),
('Bodoco', 17),
('Bom Conselho', 17),
('Bom Jardim', 17),
('Bonito', 17),
('Brejao', 17),
('Brejinho', 17),
('Brejo da Madre de Deus', 17),
('Buenos Aires', 17),
('Buique', 17),
('Cabo de Santo Agostinho', 17),
('Cabrobo', 17),
('Cachoeirinha', 17),
('Caetes', 17),
('Calcado', 17),
('Calumbi', 17),
('Camaragibe', 17),
('Camocim de Sao Felix', 17),
('Camutanga', 17),
('Canhotinho', 17),
('Capoeiras', 17),
('Carnaiba', 17),
('Carnaubeira da Penha', 17),
('Carpina', 17),
('Caruaru', 17),
('Casinhas', 17),
('Catende', 17),
('Cedro', 17),
('Cha Grande', 17),
('Cha de Alegria', 17),
('Condado', 17),
('Correntes', 17),
('Cortes', 17),
('Cumaru', 17),
('Cupira', 17),
('Custodia', 17),
('Dormentes', 17),
('Escada', 17),
('Exu', 17),
('Feira Nova', 17),
('Ferreiros', 17),
('Flores', 17),
('Floresta', 17),
('Frei Miguelinho', 17),
('Gameleira', 17),
('Garanhuns', 17),
('Gloria do Goita', 17),
('Goiana', 17),
('Granito', 17),
('Gravata', 17),
('Iati', 17),
('Ibimirim', 17),
('Ibirajuba', 17),
('Igarassu', 17),
('Iguaraci', 17),
('Inaja', 17),
('Ingazeira', 17),
('Ipojuca', 17),
('Ipubi', 17),
('Itacuruba', 17),
('Itaiba', 17),
('Itamaraca', 17),
('Itambe', 17),
('Itapetim', 17),
('Itapissuma', 17),
('Itaquitinga', 17),
('Jaboatao dos Guararapes', 17),
('Jaqueira', 17),
('Jatauba', 17),
('Jatoba', 17),
('Joao Alfredo', 17),
('Joaquim Nabuco', 17),
('Jucati', 17),
('Jupi', 17),
('Jurema', 17),
('Lagoa Grande', 17),
('Lagoa do Carro', 17),
('Lagoa do Itaenga', 17),
('Lagoa do Ouro', 17),
('Lagoa dos Gatos', 17),
('Lajedo', 17),
('Limoeiro', 17),
('Macaparana', 17),
('Machados', 17),
('Manari', 17),
('Maraial', 17),
('Mirandiba', 17),
('Moreilandia', 17),
('Moreno', 17),
('Nazare da Mata', 17),
('Olinda', 17),
('Orobo', 17),
('Oroco', 17),
('Ouricuri', 17),
('Palmares', 17),
('Palmeirina', 17),
('Panelas', 17),
('Paranatama', 17),
('Parnamirim', 17),
('Passira', 17),
('Paudalho', 17),
('Paulista', 17),
('Pedra', 17),
('Pesqueira', 17),
('Petrolandia', 17),
('Petrolina', 17),
('Pocao', 17),
('Pombos', 17),
('Primavera', 17),
('Quipapa', 17),
('Quixaba', 17),
('Recife', 17),
('Riacho das Almas', 17),
('Ribeirao', 17),
('Rio Formoso', 17),
('Saire', 17),
('Salgadinho', 17),
('Salgueiro', 17),
('Saloa', 17),
('Sanharo', 17),
('Santa Cruz da Baixa Verde', 17),
('Santa Cruz do Capibaribe', 17),
('Santa Cruz', 17),
('Santa Filomena', 17),
('Santa Maria da Boa Vista', 17),
('Santa Maria do Cambuca', 17),
('Santa Terezinha', 17),
('Sao Benedito do Sul', 17),
('Sao Bento do Una', 17),
('Sao Caitano', 17),
('Sao Joao', 17),
('Sao Joaquim do Monte', 17),
('Sao Jose da Coroa Grande', 17),
('Sao Jose do Belmonte', 17),
('Sao Jose do Egito', 17),
('Sao Lourenco da Mata', 17),
('Sao Vicente Ferrer', 17),
('Serra Talhada', 17),
('Serrita', 17),
('Sertania', 17),
('Sirinhaem', 17),
('Solidao', 17),
('Surubim', 17),
('Tabira', 17),
('Tacaimbo', 17),
('Tacaratu', 17),
('Tamandare', 17),
('Taquaritinga do Norte', 17),
('Terezinha', 17),
('Terra Nova', 17),
('Timbauba', 17),
('Toritama', 17),
('Tracunhaem', 17),
('Trindade', 17),
('Triunfo', 17),
('Tupanatinga', 17),
('Tuparetama', 17),
('Venturosa', 17),
('Verdejante', 17),
('Vertente do Lerio', 17),
('Vertentes', 17),
('Vicencia', 17),
('Vitoria de Santo Antao', 17),
('Xexeu', 17);
