INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abaiara', 6),
('Acarape', 6),
('Acarau', 6),
('Acopiara', 6),
('Aiuaba', 6),
('Alcantaras', 6),
('Altaneira', 6),
('Alto Santo', 6),
('Amontada', 6),
('Antonina do Norte', 6),
('Apuiares', 6),
('Aquiraz', 6),
('Aracati', 6),
('Aracoiaba', 6),
('Ararenda', 6),
('Araripe', 6),
('Aratuba', 6),
('Arneiroz', 6),
('Assare', 6),
('Aurora', 6),
('Baixio', 6),
('Banabuiu', 6),
('Barbalha', 6),
('Barreira', 6),
('Barro', 6),
('Barroquinha', 6),
('Baturite', 6),
('Beberibe', 6),
('Bela Cruz', 6),
('Boa Viagem', 6),
('Brejo Santo', 6),
('Camocim', 6),
('Campos Sales', 6),
('Caninde', 6),
('Capistrano', 6),
('Caridade', 6),
('Carire', 6),
('Caririacu', 6),
('Carius', 6),
('Carnaubal', 6),
('Cascavel', 6),
('Catarina', 6),
('Catunda', 6),
('Caucaia', 6),
('Cedro', 6),
('Chaval', 6),
('Choro', 6),
('Chorozinho', 6),
('Coreau', 6),
('Crateus', 6),
('Crato', 6),
('Croata', 6),
('Cruz', 6),
('Deputado Irapuan Pinheiro', 6),
('Erere', 6),
('Eusebio', 6),
('Farias Brito', 6),
('Forquilha', 6),
('Fortaleza', 6),
('Fortim', 6),
('Frecheirinha', 6),
('General Sampaio', 6),
('Graca', 6),
('Granja', 6),
('Granjeiro', 6),
('Groairas', 6),
('Guaiuba', 6),
('Guaraciaba do Norte', 6),
('Guaramiranga', 6),
('Hidrolandia', 6),
('Horizonte', 6),
('Ibaretama', 6),
('Ibiapina', 6),
('Ibicuitinga', 6),
('Icapui', 6),
('Ico', 6),
('Iguatu', 6),
('Independencia', 6),
('Ipaporanga', 6),
('Ipaumirim', 6),
('Ipu', 6),
('Ipueiras', 6),
('Iracema', 6),
('Iraucuba', 6),
('Itaicaba', 6),
('Itaitinga', 6),
('Itapage', 6),
('Itapipoca', 6),
('Itapiuna', 6),
('Itarema', 6),
('Itatira', 6),
('Jaguaretama', 6),
('Jaguaribara', 6),
('Jaguaribe', 6),
('Jaguaruana', 6),
('Jardim', 6),
('Jati', 6),
('Jijoca de Jericoacoara', 6),
('Juazeiro do Norte', 6),
('Jucas', 6),
('Lavras da Mangabeira', 6),
('Limoeiro do Norte', 6),
('Madalena', 6),
('Maracanau', 6),
('Maranguape', 6),
('Marco', 6),
('Martinopole', 6),
('Massape', 6),
('Mauriti', 6),
('Meruoca', 6),
('Milagres', 6),
('Milha', 6),
('Miraima', 6),
('Missao Velha', 6),
('Mombaca', 6),
('Monsenhor Tabosa', 6),
('Morada Nova', 6),
('Moraujo', 6),
('Morrinhos', 6),
('Mucambo', 6),
('Mulungu', 6),
('Nova Olinda', 6),
('Nova Russas', 6),
('Novo Oriente', 6),
('Ocara', 6),
('Oros', 6),
('Pacajus', 6),
('Pacatuba', 6),
('Pacoti', 6),
('Pacuja', 6),
('Palhano', 6),
('Palmacia', 6),
('Paracuru', 6),
('Paraipaba', 6),
('Parambu', 6),
('Paramoti', 6),
('Pedra Branca', 6),
('Penaforte', 6),
('Pentecoste', 6),
('Pereiro', 6),
('Pindoretama', 6),
('Piquet Carneiro', 6),
('Pires Ferreira', 6),
('Poranga', 6),
('Porteiras', 6),
('Potengi', 6),
('Potiretama', 6),
('Quiterianopolis', 6),
('Quixada', 6),
('Quixela', 6),
('Quixeramobim', 6),
('Quixere', 6),
('Redencao', 6),
('Reriutaba', 6),
('Russas', 6),
('Saboeiro', 6),
('Salitre', 6),
('Santa Quiteria', 6),
('Santana do Acarau', 6),
('Santana do Cariri', 6),
('Sao Benedito', 6),
('Sao Goncalo do Amarante', 6),
('Sao Joao do Jaguaribe', 6),
('Sao Luis do Curu', 6),
('Senador Pompeu', 6),
('Senador Sa', 6),
('Sobral', 6),
('Solonopole', 6),
('Tabuleiro do Norte', 6),
('Tamboril', 6),
('Tarrafas', 6),
('Taua', 6),
('Tejucuoca', 6),
('Tiangua', 6),
('Trairi', 6),
('Tururu', 6),
('Ubajara', 6),
('Umari', 6),
('Umirim', 6),
('Uruburetama', 6),
('Uruoca', 6),
('Varjota', 6),
('Varzea Alegre', 6),
('Vicosa do Ceara', 6);