INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abreulandia', 27),
('Aguiarnopolis', 27),
('Alianca do Tocantins', 27),
('Almas', 27),
('Alvorada', 27),
('Ananas', 27),
('Angico', 27),
('Aparecida do Rio Negro', 27),
('Aragominas', 27),
('Araguacema', 27),
('Araguacu', 27),
('Araguaina', 27),
('Araguana', 27),
('Araguatins', 27),
('Arapoema', 27),
('Arraias', 27),
('Augustinopolis', 27),
('Aurora do Tocantins', 27),
('Axixa do Tocantins', 27),
('Babaculandia', 27),
('Bandeirantes do Tocantins', 27),
('Barra do Ouro', 27),
('Barrolandia', 27),
('Bernardo Sayao', 27),
('Bom Jesus do Tocantins', 27),
('Brasilandia do Tocantins', 27),
('Brejinho de Nazare', 27),
('Buriti do Tocantins', 27),
('Cachoeirinha', 27),
('Campos Lindos', 27),
('Cariri do Tocantins', 27),
('Carmolandia', 27),
('Carrasco Bonito', 27),
('Caseara', 27),
('Centenario', 27),
('Chapada da Natividade', 27),
('Chapada de Areia', 27),
('Colinas do Tocantins', 27),
('Colmeia', 27),
('Combinado', 27),
('Conceicao do Tocantins', 27),
('Couto de Magalhaes', 27),
('Cristalandia', 27),
('Crixas do Tocantins', 27),
('Darcinopolis', 27),
('Dianopolis', 27),
('Divinopolis do Tocantins', 27),
('Dois Irmaos do Tocantins', 27),
('Duere', 27),
('Esperantina', 27),
('Fatima', 27),
('Figueiropolis', 27),
('Filadelfia', 27),
('Formoso do Araguaia', 27),
('Fortaleza do Tabocao', 27),
('Goianorte', 27),
('Goiatins', 27),
('Guarai', 27),
('Gurupi', 27),
('Ipueiras', 27),
('Itacaja', 27),
('Itaguatins', 27),
('Itapiratins', 27),
('Itapora do Tocantins', 27),
('Jau do Tocantins', 27),
('Juarina', 27),
('Lagoa da Confusao', 27),
('Lagoa do Tocantins', 27),
('Lajeado', 27),
('Lavandeira', 27),
('Lizarda', 27),
('Luzinopolis', 27),
('Marianopolis do Tocantins', 27),
('Mateiros', 27),
('Maurilandia do Tocantins', 27),
('Miracema do Tocantins', 27),
('Miranorte', 27),
('Monte Santo do Tocantins', 27),
('Monte do Carmo', 27),
('Mosquito', 27),
('Muricilandia', 27),
('Natividade', 27),
('Nazare', 27),
('Nova Olinda', 27),
('Nova Rosalandia', 27),
('Novo Acordo', 27),
('Novo Alegre', 27),
('Novo Jardim', 27),
('Oliveira de Fatima', 27),
('Palmas', 27),
('Palmeirante', 27),
('Palmeiropolis', 27),
('Paraiso do Tocantins', 27),
('Parana', 27),
('Pau d\'Arco', 27),
('Pedro Afonso', 27),
('Peixe', 27),
('Pequizeiro', 27),
('Pindorama do Tocantins', 27),
('Piraque', 27),
('Pium', 27),
('Ponte Alta do Bom Jesus', 27),
('Ponte Alta do Tocantins', 27),
('Porto Alegre do Tocantins', 27),
('Porto Nacional', 27),
('Praia Norte', 27),
('Presidente Kennedy', 27),
('Pugmil', 27),
('Recursolandia', 27),
('Riachinho', 27),
('Rio Sono', 27),
('Rio da Conceicao', 27),
('Rio dos Bois', 27),
('Sampaio', 27),
('Sandolandia', 27),
('Santa Fe do Araguaia', 27),
('Santa Maria do Tocantins', 27),
('Santa Rita do Tocantins', 27),
('Santa Rosa do Tocantins', 27),
('Santa Tereza do Tocantins', 27),
('Santa Terezinha do Tocantins', 27),
('Sao Bento do Tocantins', 27),
('Sao Felix do Tocantins', 27),
('Sao Miguel do Tocantins', 27),
('Sao Salvador do Tocantins', 27),
('Sao Sebastiao do Tocantins', 27),
('Sao Valerio da Natividade', 27),
('Silvanopolis', 27),
('Sitio Novo do Tocantins', 27),
('Sucupira', 27),
('Taguatinga', 27),
('Taipas do Tocantins', 27),
('Talisma', 27),
('Tocantinia', 27),
('Tocantinopolis', 27),
('Tupirama', 27),
('Tupiratins', 27),
('Wanderlandia', 27),
('Xambioa', 27);