INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Acailandia', 10),
('Afonso Cunha', 10),
('Agua Doce do Maranhao', 10),
('Alcantara', 10),
('Aldeias Altas', 10),
('Altamira do Maranhao', 10),
('Alto Alegre do Maranhao', 10),
('Alto Alegre do Pindare', 10),
('Alto Parnaiba', 10),
('Amapa do Maranhao', 10),
('Amarante do Maranhao', 10),
('Anajatuba', 10),
('Anapurus', 10),
('Apicum-Acu', 10),
('Araguana', 10),
('Araioses', 10),
('Arame', 10),
('Arari', 10),
('Axixa', 10),
('Bacabal', 10),
('Bacabeira', 10),
('Bacuri', 10),
('Bacurituba', 10),
('Balsas', 10),
('Barao de Grajau', 10),
('Barra do Corda', 10),
('Barreirinhas', 10),
('Bela Vista do Maranhao', 10),
('Belagua', 10),
('Benedito Leite', 10),
('Bequimao', 10),
('Bernardo do Mearim', 10),
('Boa Vista do Gurupi', 10),
('Bom Jardim', 10),
('Bom Jesus das Selvas', 10),
('Bom Lugar', 10),
('Brejo de Areia', 10),
('Brejo', 10),
('Buriti Bravo', 10),
('Buriti', 10),
('Buriticupu', 10),
('Buritirama', 10),
('Cachoeira Grande', 10),
('Cajapio', 10),
('Cajari', 10),
('Campestre do Maranhao', 10),
('Candido Mendes', 10),
('Cantanhede', 10),
('Capinzal do Norte', 10),
('Carolina', 10),
('Carutapera', 10),
('Caxias', 10),
('Cedral', 10),
('Central do Maranhao', 10),
('Centro Novo do Maranhao', 10),
('Centro do Guilherme', 10),
('Chapadinha', 10),
('Cidelandia', 10),
('Codo', 10),
('Coelho Neto', 10),
('Colinas', 10),
('Conceicao do Lago-Acu', 10),
('Coroata', 10),
('Cururupu', 10),
('Davinopolis', 10),
('Dom Pedro', 10),
('Duque Bacelar', 10),
('Esperantinopolis', 10),
('Estreito', 10),
('Feira Nova do Maranhao', 10),
('Fernando Falcao', 10),
('Formosa da Serra Negra', 10),
('Fortaleza dos Nogueiras', 10),
('Fortuna', 10),
('Godofredo Viana', 10),
('Goncalves Dias', 10),
('Governador Archer', 10),
('Governador Edison Lobao', 10),
('Governador Eugenio Barros', 10),
('Governador Luiz Rocha', 10),
('Governador Newton Bello', 10),
('Governador Nunes Freire', 10),
('Graca Aranha', 10),
('Grajau', 10),
('Guimaraes', 10),
('Humberto de Campos', 10),
('Icatu', 10),
('Igarape Grande', 10),
('Igarape do Meio', 10),
('Imperatriz', 10),
('Itaipava do Grajau', 10),
('Itapecuru Mirim', 10),
('Itinga do Maranhao', 10),
('Jatoba', 10),
('Jenipapo dos Vieiras', 10),
('Joao Lisboa', 10),
('Joselandia', 10),
('Junco do Maranhao', 10),
('Lago Verde', 10),
('Lago da Pedra', 10),
('Lago do Junco', 10),
('Lagoa Grande do Maranhao', 10),
('Lagoa do Mato', 10),
('Lagoa dos Rodrigues', 10),
('Lajeado Novo', 10),
('Lima Campos', 10),
('Loreto', 10),
('Luis Domingues', 10),
('Magalhaes de Almeida', 10),
('Maracacume', 10),
('Maraja do Sena', 10),
('Maranhaozinho', 10),
('Mata Roma', 10),
('Matinha', 10),
('Matoes do Norte', 10),
('Matoes', 10),
('Milagres do Maranhao', 10),
('Mirador', 10),
('Miranda do Norte', 10),
('Mirinzal', 10),
('Moncao', 10),
('Montes Altos', 10),
('Morros', 10),
('Nina Rodrigues', 10),
('Nova Colinas', 10),
('Nova Iorque', 10),
('Nova Olinda do Maranhao', 10),
('Olho d\'Agua das Cunhas', 10),
('Olinda Nova do Maranhao', 10),
('Paco do Lumiar', 10),
('Palmeirandia', 10),
('Paraibano', 10),
('Parnarama', 10),
('Passagem Franca', 10),
('Pastos Bons', 10),
('Paulino Neves', 10),
('Paulo Ramos', 10),
('Pedreiras', 10),
('Pedro do Rosario', 10),
('Penalva', 10),
('Peri Mirim', 10),
('Peritoro', 10),
('Pindare Mirim', 10),
('Pinheiro', 10),
('Pio XII', 10),
('Pirapemas', 10),
('Pocao de Pedras', 10),
('Porto Franco', 10),
('Porto Rico do Maranhao', 10),
('Presidente Dutra', 10),
('Presidente Juscelino', 10),
('Presidente Medici', 10),
('Presidente Sarney', 10),
('Presidente Vargas', 10),
('Primeira Cruz', 10),
('Raposa', 10),
('Riachao', 10),
('Ribamar Fiquene', 10),
('Rosario', 10),
('Sambaiba', 10),
('Santa Filomena do Maranhao', 10),
('Santa Helena', 10),
('Santa Ines', 10),
('Santa Luzia do Parua', 10),
('Santa Luzia', 10),
('Santa Quiteria do Maranhao', 10),
('Santa Rita', 10),
('Santana do Maranhao', 10),
('Santo Amaro do Maranhao', 10),
('Santo Antonio dos Lopes', 10),
('Sao Benedito do Rio Preto', 10),
('Sao Bento', 10),
('Sao Bernardo', 10),
('Sao Domingos do Azeitao', 10),
('Sao Domingos do Maranhao', 10),
('Sao Felix de Balsas', 10),
('Sao Francisco do Brejao', 10),
('Sao Francisco do Maranhao', 10),
('Sao Joao Batista', 10),
('Sao Joao do Caru', 10),
('Sao Joao do Paraiso', 10),
('Sao Joao do Soter', 10),
('Sao Joao dos Patos', 10),
('Sao Jose de Ribamar', 10),
('Sao Jose dos Basilios', 10),
('Sao Luis Gonzaga do Maranhao', 10),
('Sao Luis', 10),
('Sao Mateus do Maranhao', 10),
('Sao Pedro da Agua Branca', 10),
('Sao Pedro dos Crentes', 10),
('Sao Raimundo das Mangabeiras', 10),
('Sao Raimundo do Doca Bezerra', 10),
('Sao Roberto', 10),
('Sao Vicente Ferrer', 10),
('Satubinha', 10),
('Senador Alexandre Costa', 10),
('Senador La Rocque', 10),
('Serrano do Maranhao', 10),
('Sitio Novo', 10),
('Sucupira do Norte', 10),
('Sucupira do Riachao', 10),
('Tasso Fragoso', 10),
('Timbiras', 10),
('Timon', 10),
('Trizidela do Vale', 10),
('Tufilandia', 10),
('Tuntum', 10),
('Turiacu', 10),
('Turilandia', 10),
('Tutoia', 10),
('Urbano Santos', 10),
('Vargem Grande', 10),
('Viana', 10),
('Vila Nova dos Martirios', 10),
('Vitoria do Mearim', 10),
('Vitorino Freire', 10),
('Ze Doca', 10);