INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Acari', 20),
('Acu', 20),
('Afonso Bezerra', 20),
('Agua Nova', 20),
('Alexandria', 20),
('Almino Afonso', 20),
('Alto do Rodrigues', 20),
('Angicos', 20),
('Antonio Martins', 20),
('Apodi', 20),
('Areia Branca', 20),
('Ares', 20),
('Augusto Severo', 20),
('Baia Formosa', 20),
('Barauna', 20),
('Barcelona', 20),
('Bento Fernandes', 20),
('Bodo', 20),
('Bom Jesus', 20),
('Brejinho', 20),
('Caicara do Norte', 20),
('Caicara do Rio do Vento', 20),
('Caico', 20),
('Campo Redondo', 20),
('Canguaretama', 20),
('Caraubas', 20),
('Carnauba dos Dantas', 20),
('Carnaubais', 20),
('Ceara-Mirim', 20),
('Cerro Cora', 20),
('Coronel Ezequiel', 20),
('Coronel Joao Pessoa', 20),
('Cruzeta', 20),
('Currais Novos', 20),
('Doutor Severiano', 20),
('Encanto', 20),
('Equador', 20),
('Espirito Santo', 20),
('Extremoz', 20),
('Felipe Guerra', 20),
('Fernando Pedroza', 20),
('Florania', 20),
('Francisco Dantas', 20),
('Frutuoso Gomes', 20),
('Galinhos', 20),
('Goianinha', 20),
('Governador Dix-Sept Rosado', 20),
('Grossos', 20),
('Guamare', 20),
('Ielmo Marinho', 20),
('Ipanguacu', 20),
('Ipueira', 20),
('Itaja', 20),
('Itau', 20),
('Jacana', 20),
('Jandaira', 20),
('Janduis', 20),
('Januario Cicco', 20),
('Japi', 20),
('Jardim de Angicos', 20),
('Jardim de Piranhas', 20),
('Jardim do Serido', 20),
('Joao Camara', 20),
('Joao Dias', 20),
('Jose da Penha', 20),
('Jucurutu', 20),
('Lagoa Nova', 20),
('Lagoa Salgada', 20),
('Lagoa d\'Anta', 20),
('Lagoa de Pedras', 20),
('Lagoa de Velhos', 20),
('Lajes Pintadas', 20),
('Lajes', 20),
('Lucrecia', 20),
('Luis Gomes', 20),
('Macaiba', 20),
('Macau', 20),
('Major Sales', 20),
('Marcelino Vieira', 20),
('Martins', 20),
('Maxaranguape', 20),
('Messias Targino', 20),
('Montanhas', 20),
('Monte Alegre', 20),
('Monte das Gameleiras', 20),
('Mossoro', 20),
('Natal', 20),
('Nisia Floresta', 20),
('Nova Cruz', 20),
('Olho-d\'Agua do Borges', 20),
('Ouro Branco', 20),
('Parana', 20),
('Parau', 20),
('Parazinho', 20),
('Parelhas', 20),
('Parnamirim', 20),
('Passa e Fica', 20),
('Passagem', 20),
('Patu', 20),
('Pau dos Ferros', 20),
('Pedra Grande', 20),
('Pedra Preta', 20),
('Pedro Avelino', 20),
('Pedro Velho', 20),
('Pendencias', 20),
('Piloes', 20),
('Poco Branco', 20),
('Portalegre', 20),
('Porto do Mangue', 20),
('Presidente Juscelino', 20),
('Pureza', 20),
('Rafael Fernandes', 20),
('Rafael Godeiro', 20),
('Riacho da Cruz', 20),
('Riacho de Santana', 20),
('Riachuelo', 20),
('Rio do Fogo', 20),
('Rodolfo Fernandes', 20),
('Ruy Barbosa', 20),
('Santa Cruz', 20),
('Santa Maria', 20),
('Santana do Matos', 20),
('Santana do Serido', 20),
('Santo Antonio', 20),
('Sao Bento do Norte', 20),
('Sao Bento do Trairi', 20),
('Sao Fernando', 20),
('Sao Francisco do Oeste', 20),
('Sao Goncalo do Amarante', 20),
('Sao Joao do Sabugi', 20),
('Sao Jose de Mipibu', 20),
('Sao Jose do Campestre', 20),
('Sao Jose do Serido', 20),
('Sao Miguel de Touros', 20),
('Sao Miguel', 20),
('Sao Paulo do Potengi', 20),
('Sao Pedro', 20),
('Sao Rafael', 20),
('Sao Tome', 20),
('Sao Vicente', 20),
('Senador Eloi de Souza', 20),
('Senador Georgino Avelino', 20),
('Serra Negra do Norte', 20),
('Serra de Sao Bento', 20),
('Serra do Mel', 20),
('Serrinha dos Pintos', 20),
('Serrinha', 20),
('Severiano Melo', 20),
('Sitio Novo', 20),
('Taboleiro Grande', 20),
('Taipu', 20),
('Tangara', 20),
('Tenente Ananias', 20),
('Tenente Laurentino Cruz', 20),
('Tibau do Sul', 20),
('Tibau', 20),
('Timbauba dos Batistas', 20),
('Touros', 20),
('Triunfo Potiguar', 20),
('Umarizal', 20),
('Upanema', 20),
('Varzea', 20),
('Venha-Ver', 20),
('Vera Cruz', 20),
('Vicosa', 20),
('Vila Flor', 20);