INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Alta Floresta d\'Oeste', 22),
('Alto Alegre do Parecis', 22),
('Alto Paraiso', 22),
('Alvorada d\'Oeste', 22),
('Ariquemes', 22),
('Buritis', 22),
('Cabixi', 22),
('Cacaulandia', 22),
('Cacoal', 22),
('Campo Novo de Rondonia', 22),
('Candeias do Jamari', 22),
('Castanheiras', 22),
('Cerejeiras', 22),
('Chupinguaia', 22),
('Colorado do Oeste', 22),
('Corumbiara', 22),
('Costa Marques', 22),
('Cujubim', 22),
('Espigao d\'Oeste', 22),
('Governador Jorge Teixeira', 22),
('Guajara-Mirim', 22),
('Jamari', 22),
('Jaru', 22),
('Ji-Parana', 22),
('Machadinho d\'Oeste', 22),
('Ministro Andreazza', 22),
('Mirante da Serra', 22),
('Monte Negro', 22),
('Nova Brasilandia d\'Oeste', 22),
('Nova Mamore', 22),
('Nova Uniao', 22),
('Novo Horizonte do Oeste', 22),
('Ouro Preto do Oeste', 22),
('Parecis', 22),
('Pimenta Bueno', 22),
('Pimenteiras do Oeste', 22),
('Porto Velho', 22),
('Presidente Medici', 22),
('Primavera de Rondonia', 22),
('Rio Crespo', 22),
('Rolim de Moura', 22),
('Santa Luzia d\'Oeste', 22),
('Sao Felipe d\'Oeste', 22),
('Sao Francisco do Guapore', 22),
('Sao Miguel do Guapore', 22),
('Seringueiras', 22),
('Teixeiropolis', 22),
('Theobroma', 22),
('Urupa', 22),
('Vale do Anari', 22),
('Vale do Paraiso', 22),
('Vilhena', 22);