INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abatia', 16),
('Adrianopolis', 16),
('Agudos do Sul', 16),
('Almirante Tamandare', 16),
('Altamira do Parana', 16),
('Altania', 16),
('Alto Parana', 16),
('Alto Piquiri', 16),
('Alvorada do Sul', 16),
('Amapora', 16),
('Ampere', 16),
('Anahy', 16),
('Andira', 16),
('Angulo', 16),
('Antonina', 16),
('Antonio Olinto', 16),
('Apucarana', 16),
('Arapongas', 16),
('Arapoti', 16),
('Arapua', 16),
('Araruna', 16),
('Araucaria', 16),
('Ariranha do Ivai', 16),
('Assai', 16),
('Assis Chateaubriand', 16),
('Astorga', 16),
('Atalaia', 16),
('Balsa Nova', 16),
('Bandeirantes', 16),
('Barbosa Ferraz', 16),
('Barra do Jacare', 16),
('Barracao', 16),
('Bela Vista da Caroba', 16),
('Bela Vista do Paraiso', 16),
('Bituruna', 16),
('Boa Esperanca do Iguacu', 16),
('Boa Esperanca', 16),
('Boa Ventura de Sao Roque', 16),
('Boa Vista da Aparecida', 16),
('Bocaiuva do Sul', 16),
('Bom Jesus do Sul', 16),
('Bom Sucesso do Sul', 16),
('Bom Sucesso', 16),
('Borrazopolis', 16),
('Braganey', 16),
('Brasilandia do Sul', 16),
('Cafeara', 16),
('Cafelandia', 16),
('Cafezal do Sul', 16),
('California', 16),
('Cambara', 16),
('Cambe', 16),
('Cambira', 16),
('Campina Grande do Sul', 16),
('Campina da Lagoa', 16),
('Campina do Simao', 16),
('Campo Bonito', 16),
('Campo Largo', 16),
('Campo Magro', 16),
('Campo Mourao', 16),
('Campo do Tenente', 16),
('Candido de Abreu', 16),
('Candoi', 16),
('Cantagalo', 16),
('Capanema', 16),
('Capitao Leonidas Marques', 16),
('Carambei', 16),
('Carlopolis', 16),
('Cascavel', 16),
('Castro', 16),
('Catanduvas', 16),
('Centenario do Sul', 16),
('Cerro Azul', 16),
('Ceu Azul', 16),
('Chopinzinho', 16),
('Cianorte', 16),
('Cidade Gaucha', 16),
('Clevelandia', 16),
('Colombo', 16),
('Colorado', 16),
('Congonhinhas', 16),
('Conselheiro Mairinck', 16),
('Contenda', 16),
('Corbelia', 16),
('Cornelio Procopio', 16),
('Coronel Domingos Soares', 16),
('Coronel Vivida', 16),
('Corumbatai do Sul', 16),
('Cruz Machado', 16),
('Cruzeiro do Iguacu', 16),
('Cruzeiro do Oeste', 16),
('Cruzeiro do Sul', 16),
('Cruzmaltina', 16),
('Curitiba', 16),
('Curiuva', 16),
('Diamante d\'Oeste', 16),
('Diamante do Norte', 16),
('Diamante do Sul', 16),
('Dois Vizinhos', 16),
('Douradina', 16),
('Doutor Camargo', 16),
('Doutor Ulysses', 16),
('Eneas Marques', 16),
('Engenheiro Beltrao', 16),
('Entre Rios do Oeste', 16),
('Esperanca Nova', 16),
('Espigao Alto do Iguacu', 16),
('Farol', 16),
('Faxinal', 16),
('Fazenda Rio Grande', 16),
('Fenix', 16),
('Fernandes Pinheiro', 16),
('Figueira', 16),
('Flor da Serra do Sul', 16),
('Florai', 16),
('Floresta', 16),
('Florestopolis', 16),
('Florida', 16),
('Formosa do Oeste', 16),
('Foz do Iguacu', 16),
('Foz do Jordao', 16),
('Francisco Alves', 16),
('Francisco Beltrao', 16),
('General Carneiro', 16),
('Godoy Moreira', 16),
('Goioere', 16),
('Goioxim', 16),
('Grandes Rios', 16),
('Guaira', 16),
('Guairaca', 16),
('Guamiranga', 16),
('Guapirama', 16),
('Guaporema', 16),
('Guaraci', 16),
('Guaraniacu', 16),
('Guarapuava', 16),
('Guaraquecaba', 16),
('Guaratuba', 16),
('Honorio Serpa', 16),
('Ibaiti', 16),
('Ibema', 16),
('Ibipora', 16),
('Icaraima', 16),
('Iguaracu', 16),
('Iguatu', 16),
('Imbau', 16),
('Imbituva', 16),
('Inacio Martins', 16),
('Inaja', 16),
('Indianopolis', 16),
('Ipiranga', 16),
('Ipora', 16),
('Iracema do Oeste', 16),
('Irati', 16),
('Iretama', 16),
('Itaguaje', 16),
('Itaipulandia', 16),
('Itambaraca', 16),
('Itambe', 16),
('Itapejara d\'Oeste', 16),
('Itaperucu', 16),
('Itauna do Sul', 16),
('Ivai', 16),
('Ivaipora', 16),
('Ivate', 16),
('Ivatuba', 16),
('Jaboti', 16),
('Jacarezinho', 16),
('Jaguapita', 16),
('Jaguariaiva', 16),
('Jandaia do Sul', 16),
('Janiopolis', 16),
('Japira', 16),
('Japura', 16),
('Jardim Alegre', 16),
('Jardim Olinda', 16),
('Jataizinho', 16),
('Jesuitas', 16),
('Joaquim Tavora', 16),
('Jundiai do Sul', 16),
('Juranda', 16),
('Jussara', 16),
('Kalore', 16),
('Lapa', 16),
('Laranjal', 16),
('Laranjeiras do Sul', 16),
('Leopolis', 16),
('Lidianopolis', 16),
('Lindoeste', 16),
('Loanda', 16),
('Lobato', 16),
('Londrina', 16),
('Luiziana', 16),
('Lunardelli', 16),
('Lupionopolis', 16),
('Mallet', 16),
('Mambore', 16),
('Mandaguacu', 16),
('Mandaguari', 16),
('Mandirituba', 16),
('Manfrinopolis', 16),
('Mangueirinha', 16),
('Manoel Ribas', 16),
('Marechal Candido Rondon', 16),
('Maria Helena', 16),
('Marialva', 16),
('Marilandia do Sul', 16),
('Marilena', 16),
('Mariluz', 16),
('Maringa', 16),
('Mariopolis', 16),
('Maripa', 16),
('Marmeleiro', 16),
('Marquinho', 16),
('Marumbi', 16),
('Matelandia', 16),
('Matinhos', 16),
('Mato Rico', 16),
('Maua da Serra', 16),
('Medianeira', 16),
('Mercedes', 16),
('Mirador', 16),
('Miraselva', 16),
('Missal', 16),
('Moreira Sales', 16),
('Morretes', 16),
('Munhoz de Melo', 16),
('Nossa Senhora das Gracas', 16),
('Nova Alianca do Ivai', 16),
('Nova America da Colina', 16),
('Nova Aurora', 16),
('Nova Cantu', 16),
('Nova Esperanca do Sudoeste', 16),
('Nova Esperanca', 16),
('Nova Fatima', 16),
('Nova Laranjeiras', 16),
('Nova Londrina', 16),
('Nova Olimpia', 16),
('Nova Prata do Iguacu', 16),
('Nova Santa Barbara', 16),
('Nova Santa Rosa', 16),
('Nova Tebas', 16),
('Novo Itacolomi', 16),
('Ortigueira', 16),
('Ourizona', 16),
('Ouro Verde do Oeste', 16),
('Paicandu', 16),
('Palmas', 16),
('Palmeira', 16),
('Palmital', 16),
('Palotina', 16),
('Paraiso do Norte', 16),
('Paranacity', 16),
('Paranagua', 16),
('Paranapoema', 16),
('Paranavai', 16),
('Pato Bragado', 16),
('Pato Branco', 16),
('Paula Freitas', 16),
('Paulo Frontin', 16),
('Peabiru', 16),
('Perobal', 16),
('Perola d\'Oeste', 16),
('Perola', 16),
('Pien', 16),
('Pinhais', 16),
('Pinhal de Sao Bento', 16),
('Pinhalao', 16),
('Pinhao', 16),
('Pirai do Sul', 16),
('Piraquara', 16),
('Pitanga', 16),
('Pitangueiras', 16),
('Planaltina do Parana', 16),
('Planalto', 16),
('Ponta Grossa', 16),
('Pontal do Parana', 16),
('Porecatu', 16),
('Porto Amazonas', 16),
('Porto Barreiro', 16),
('Porto Rico', 16),
('Porto Vitoria', 16),
('Prado Ferreira', 16),
('Pranchita', 16),
('Presidente Castelo Branco', 16),
('Primeiro de Maio', 16),
('Prudentopolis', 16),
('Quarto Centenario', 16),
('Quatigua', 16),
('Quatro Barras', 16),
('Quatro Pontes', 16),
('Quedas do Iguacu', 16),
('Querencia do Norte', 16),
('Quinta do Sol', 16),
('Quitandinha', 16),
('Ramilandia', 16),
('Rancho Alegre d\'Oeste', 16),
('Rancho Alegre', 16),
('Realeza', 16),
('Reboucas', 16),
('Renascenca', 16),
('Reserva do Iguacu', 16),
('Reserva', 16),
('Ribeirao Claro', 16),
('Ribeirao do Pinhal', 16),
('Rio Azul', 16),
('Rio Bom', 16),
('Rio Bonito do Iguacu', 16),
('Rio Branco do Ivai', 16),
('Rio Branco do Sul', 16),
('Rio Negro', 16),
('Rolandia', 16),
('Roncador', 16),
('Rondon', 16),
('Rosario do Ivai', 16),
('Sabaudia', 16),
('Salgado Filho', 16),
('Salto do Itarare', 16),
('Salto do Lontra', 16),
('Santa Amelia', 16),
('Santa Cecilia do Pavao', 16),
('Santa Cruz de Monte Castelo', 16),
('Santa Fe', 16),
('Santa Helena', 16),
('Santa Ines', 16),
('Santa Isabel do Ivai', 16),
('Santa Izabel do Oeste', 16),
('Santa Lucia', 16),
('Santa Maria do Oeste', 16),
('Santa Mariana', 16),
('Santa Monica', 16),
('Santa Tereza do Oeste', 16),
('Santa Terezinha de Itaipu', 16),
('Santana do Itarare', 16),
('Santo Antonio da Platina', 16),
('Santo Antonio do Caiua', 16),
('Santo Antonio do Paraiso', 16),
('Santo Antonio do Sudoeste', 16),
('Santo Inacio', 16),
('Sao Carlos do Ivai', 16),
('Sao Jeronimo da Serra', 16),
('Sao Joao do Caiua', 16),
('Sao Joao do Ivai', 16),
('Sao Joao do Triunfo', 16),
('Sao Joao', 16),
('Sao Jorge d\'Oeste', 16),
('Sao Jorge do Ivai', 16),
('Sao Jorge do Patrocinio', 16),
('Sao Jose da Boa Vista', 16),
('Sao Jose das Palmeiras', 16),
('Sao Jose dos Pinhais', 16),
('Sao Manoel do Parana', 16),
('Sao Mateus do Sul', 16),
('Sao Miguel do Iguacu', 16),
('Sao Pedro do Iguacu', 16),
('Sao Pedro do Ivai', 16),
('Sao Pedro do Parana', 16),
('Sao Sebastiao da Amoreira', 16),
('Sao Tome', 16),
('Sapopema', 16),
('Sarandi', 16),
('Saudade do Iguacu', 16),
('Senges', 16),
('Serranopolis do Iguacu', 16),
('Sertaneja', 16),
('Sertanopolis', 16),
('Siqueira Campos', 16),
('Sulina', 16),
('Tamarana', 16),
('Tamboara', 16),
('Tapejara', 16),
('Tapira', 16),
('Teixeira Soares', 16),
('Telemaco Borba', 16),
('Terra Boa', 16),
('Terra Rica', 16),
('Terra Roxa', 16),
('Tibagi', 16),
('Tijucas do Sul', 16),
('Toledo', 16),
('Tomazina', 16),
('Tres Barras do Parana', 16),
('Tunas do Parana', 16),
('Tuneiras do Oeste', 16),
('Tupassi', 16),
('Turvo', 16),
('Ubirata', 16),
('Umuarama', 16),
('Uniao da Vitoria', 16),
('Uniflor', 16),
('Urai', 16),
('Ventania', 16),
('Vera Cruz do Oeste', 16),
('Vere', 16),
('Vila Alta', 16),
('Virmond', 16),
('Vitorino', 16),
('Wenceslau Braz', 16),
('Xambre', 16);