INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Agua Branca', 15),
('Aguiar', 15),
('Alagoa Grande', 15),
('Alagoa Nova', 15),
('Alagoinha', 15),
('Alcantil', 15),
('Algodao de Jandaira', 15),
('Alhandra', 15),
('Amparo', 15),
('Aparecida', 15),
('Aracagi', 15),
('Arara', 15),
('Araruna', 15),
('Areia de Baraunas', 15),
('Areia', 15),
('Areial', 15),
('Aroeiras', 15),
('Assuncao', 15),
('Baia da Traicao', 15),
('Bananeiras', 15),
('Barauna', 15),
('Barra de Santa Rosa', 15),
('Barra de Santana', 15),
('Barra de Sao Miguel', 15),
('Bayeux', 15),
('Belem do Brejo do Cruz', 15),
('Belem', 15),
('Bernardino Batista', 15),
('Boa Ventura', 15),
('Boa Vista', 15),
('Bom Jesus', 15),
('Bom Sucesso', 15),
('Bonito de Santa Fe', 15),
('Boqueirao', 15),
('Borborema', 15),
('Brejo do Cruz', 15),
('Brejo dos Santos', 15),
('Caapora', 15),
('Cabaceiras', 15),
('Cabedelo', 15),
('Cachoeira dos ?ndios', 15),
('Cacimba de Areia', 15),
('Cacimba de Dentro', 15),
('Cacimbas', 15),
('Caicara', 15),
('Cajazeiras', 15),
('Cajazeirinhas', 15),
('Caldas Brandao', 15),
('Camalau', 15),
('Campina Grande', 15),
('Capim', 15),
('Caraubas', 15),
('Carrapateira', 15),
('Casserengue', 15),
('Catingueira', 15),
('Catole do Rocha', 15),
('Caturite', 15),
('Conceicao', 15),
('Condado', 15),
('Conde', 15),
('Congo', 15),
('Coremas', 15),
('Coxixola', 15),
('Cruz do Espirito Santo', 15),
('Cubati', 15),
('Cuite de Mamanguape', 15),
('Cuite', 15),
('Cuitegi', 15),
('Curral Velho', 15),
('Curral de Cima', 15),
('Damiao', 15),
('Desterro', 15),
('Diamante', 15),
('Dona Ines', 15),
('Duas Estradas', 15),
('Emas', 15),
('Esperanca', 15),
('Fagundes', 15),
('Frei Martinho', 15),
('Gado Bravo', 15),
('Guarabira', 15),
('Gurinhem', 15),
('Gurjao', 15),
('Ibiara', 15),
('Igaracy', 15),
('Imaculada', 15),
('Inga', 15),
('Itabaiana', 15),
('Itaporanga', 15),
('Itapororoca', 15),
('Itatuba', 15),
('Jacarau', 15),
('Jerico', 15),
('Joao Pessoa', 15),
('Juarez Tavora', 15),
('Juazeirinho', 15),
('Junco do Serido', 15),
('Juripiranga', 15),
('Juru', 15),
('Lagoa Seca', 15),
('Lagoa de Dentro', 15),
('Lagoa', 15),
('Lastro', 15),
('Livramento', 15),
('Logradouro', 15),
('Lucena', 15),
('Mae d\'Agua', 15),
('Malta', 15),
('Mamanguape', 15),
('Manaira', 15),
('Marcacao', 15),
('Mari', 15),
('Marizopolis', 15),
('Massaranduba', 15),
('Mataraca', 15),
('Matinhas', 15),
('Mato Grosso', 15),
('Matureia', 15),
('Mogeiro', 15),
('Montadas', 15),
('Monte Horebe', 15),
('Monteiro', 15),
('Mulungu', 15),
('Natuba', 15),
('Nazarezinho', 15),
('Nova Floresta', 15),
('Nova Olinda', 15),
('Nova Palmeira', 15),
('Olho d\'Agua', 15),
('Olivedos', 15),
('Ouro Velho', 15),
('Parari', 15),
('Passagem', 15),
('Patos', 15),
('Paulista', 15),
('Pedra Branca', 15),
('Pedra Lavrada', 15),
('Pedras de Fogo', 15),
('Pedro Regio', 15),
('Pianco', 15),
('Picui', 15),
('Pilar', 15),
('Piloes', 15),
('Piloezinhos', 15),
('Pirpirituba', 15),
('Pitimbu', 15),
('Pocinhos', 15),
('Poco Dantas', 15),
('Poco de Jose de Moura', 15),
('Pombal', 15),
('Prata', 15),
('Princesa Isabel', 15),
('Puxinana', 15),
('Queimadas', 15),
('Quixaba', 15),
('Remigio', 15),
('Riachao do Bacamarte', 15),
('Riachao do Poco', 15),
('Riachao', 15),
('Riacho de Santo Antonio', 15),
('Riacho dos Cavalos', 15),
('Rio Tinto', 15),
('Salgadinho', 15),
('Salgado de Sao Felix', 15),
('Santa Cecilia', 15),
('Santa Cruz', 15),
('Santa Helena', 15),
('Santa Ines', 15),
('Santa Luzia', 15),
('Santa Rita', 15),
('Santa Teresinha', 15),
('Santana de Mangueira', 15),
('Santana dos Garrotes', 15),
('Santarem', 15),
('Santo Andre', 15),
('Sao Bento de Pombal', 15),
('Sao Bento', 15),
('Sao Domingos de Pombal', 15),
('Sao Domingos do Cariri', 15),
('Sao Francisco', 15),
('Sao Joao do Cariri', 15),
('Sao Joao do Rio do Peixe', 15),
('Sao Joao do Tigre', 15),
('Sao Jose da Lagoa Tapada', 15),
('Sao Jose de Caiana', 15),
('Sao Jose de Espinharas', 15),
('Sao Jose de Piranhas', 15),
('Sao Jose de Princesa', 15),
('Sao Jose do Bonfim', 15),
('Sao Jose do Brejo do Cruz', 15),
('Sao Jose do Sabugi', 15),
('Sao Jose dos Cordeiros', 15),
('Sao Jose dos Ramos', 15),
('Sao Mamede', 15),
('Sao Miguel de Taipu', 15),
('Sao Sebastiao de Lagoa de Roca', 15),
('Sao Sebastiao do Umbuzeiro', 15),
('Sape', 15),
('Serido', 15),
('Serra Branca', 15),
('Serra Grande', 15),
('Serra Redonda', 15),
('Serra da Raiz', 15),
('Serraria', 15),
('Sertaozinho', 15),
('Sobrado', 15),
('Solanea', 15),
('Soledade', 15),
('Sossego', 15),
('Sousa', 15),
('Sume', 15),
('Tacima', 15),
('Taperoa', 15),
('Tavares', 15),
('Teixeira', 15),
('Tenorio', 15),
('Triunfo', 15),
('Uirauna', 15),
('Umbuzeiro', 15),
('Varzea', 15),
('Vieiropolis', 15),
('Vista Serrana', 15),
('Zabele', 15);