INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abaetetuba', 14),
('Abel Figueiredo', 14),
('Acara', 14),
('Afua', 14),
('Agua Azul do Norte', 14),
('Alenquer', 14),
('Almeirim', 14),
('Altamira', 14),
('Anajas', 14),
('Ananindeua', 14),
('Anapu', 14),
('Augusto Correa', 14),
('Aurora do Para', 14),
('Aveiro', 14),
('Bagre', 14),
('Baiao', 14),
('Bannach', 14),
('Barcarena', 14),
('Belem', 14),
('Belterra', 14),
('Benevides', 14),
('Bom Jesus do Tocantins', 14),
('Bonito', 14),
('Braganca', 14),
('Brasil Novo', 14),
('Brejo Grande do Araguaia', 14),
('Breu Branco', 14),
('Breves', 14),
('Bujaru', 14),
('Cachoeira do Arari', 14),
('Cachoeira do Piria', 14),
('Cameta', 14),
('Canaa dos Carajas', 14),
('Capanema', 14),
('Capitao Poco', 14),
('Castanhal', 14),
('Chaves', 14),
('Colares', 14),
('Conceicao do Araguaia', 14),
('Concordia do Para', 14),
('Cumaru do Norte', 14),
('Curionopolis', 14),
('Curralinho', 14),
('Curua', 14),
('Curuca', 14),
('Dom Eliseu', 14),
('Eldorado dos Carajas', 14),
('Faro', 14),
('Floresta do Araguaia', 14),
('Garrafao do Norte', 14),
('Goianesia do Para', 14),
('Gurupa', 14),
('Igarape-Acu', 14),
('Igarape-Miri', 14),
('Inhangapi', 14),
('Ipixuna do Para', 14),
('Irituia', 14),
('Itaituba', 14),
('Itupiranga', 14),
('Jacareacanga', 14),
('Jacunda', 14),
('Juruti', 14),
('Limoeiro do Ajuru', 14),
('Mae do Rio', 14),
('Magalhaes Barata', 14),
('Maraba', 14),
('Maracana', 14),
('Marapanim', 14),
('Marituba', 14),
('Medicilandia', 14),
('Melgaco', 14),
('Mocajuba', 14),
('Moju', 14),
('Monte Alegre', 14),
('Muana', 14),
('Nova Esperanca do Piria', 14),
('Nova Ipixuna', 14),
('Nova Timboteua', 14),
('Novo Progresso', 14),
('Novo Repartimento', 14),
('Obidos', 14),
('Oeiras do Para', 14),
('Oriximina', 14),
('Ourem', 14),
('Ourilandia do Norte', 14),
('Pacaja', 14),
('Palestina do Para', 14),
('Paragominas', 14),
('Parauapebas', 14),
('Pau d\'Arco', 14),
('Peixe-Boi', 14),
('Picarra', 14),
('Placas', 14),
('Ponta de Pedras', 14),
('Portel', 14),
('Porto de Moz', 14),
('Prainha', 14),
('Primavera', 14),
('Quatipuru', 14),
('Redencao', 14),
('Rio Maria', 14),
('Rondon do Para', 14),
('Ruropolis', 14),
('Salinopolis', 14),
('Salvaterra', 14),
('Santa Barbara do Para', 14),
('Santa Cruz do Arari', 14),
('Santa Isabel do Para', 14),
('Santa Luzia do Para', 14),
('Santa Maria das Barreiras', 14),
('Santa Maria do Para', 14),
('Santana do Araguaia', 14),
('Santarem Novo', 14),
('Santarem', 14),
('Santo Antonio do Taua', 14),
('Sao Caetano de Odivelas', 14),
('Sao Domingos do Araguaia', 14),
('Sao Domingos do Capim', 14),
('Sao Felix do Xingu', 14),
('Sao Francisco do Para', 14),
('Sao Geraldo do Araguaia', 14),
('Sao Joao da Ponta', 14),
('Sao Joao de Pirabas', 14),
('Sao Joao do Araguaia', 14),
('Sao Miguel do Guama', 14),
('Sao Sebastiao da Boa Vista', 14),
('Sapucaia', 14),
('Senador Jose Porfirio', 14),
('Soure', 14),
('Tailandia', 14),
('Terra Alta', 14),
('Terra Santa', 14),
('Tome-Acu', 14),
('Tracuateua', 14),
('Trairao', 14),
('Tucuma', 14),
('Tucurui', 14),
('Ulianopolis', 14),
('Uruara', 14),
('Vigia', 14),
('Viseu', 14),
('Vitoria do Xingu', 14),
('Xinguara', 14);
