INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abadia dos Dourados', 13),
('Abaete', 13),
('Abre Campo', 13),
('Acaiaca', 13),
('Acucena', 13),
('Agua Boa', 13),
('Agua Comprida', 13),
('Aguanil', 13),
('Aguas Formosas', 13),
('Aguas Vermelhas', 13),
('Aimores', 13),
('Aiuruoca', 13),
('Alagoa', 13),
('Albertina', 13),
('Alem Paraiba', 13),
('Alfenas', 13),
('Alfredo Vasconcelos', 13),
('Almenara', 13),
('Alpercata', 13),
('Alpinopolis', 13),
('Alterosa', 13),
('Alto Caparao', 13),
('Alto Jequitiba', 13),
('Alto Rio Doce', 13),
('Alvarenga', 13),
('Alvinopolis', 13),
('Alvorada de Minas', 13),
('Amparo do Serra', 13),
('Andradas', 13),
('Andrelandia', 13),
('Angelandia', 13),
('Antonio Carlos', 13),
('Antonio Dias', 13),
('Antonio Prado de Minas', 13),
('Aracai', 13),
('Aracitaba', 13),
('Aracuai', 13),
('Araguari', 13),
('Arantina', 13),
('Araponga', 13),
('Arapora', 13),
('Arapua', 13),
('Araujos', 13),
('Araxa', 13),
('Arceburgo', 13),
('Arcos', 13),
('Areado', 13),
('Argirita', 13),
('Aricanduva', 13),
('Arinos', 13),
('Astolfo Dutra', 13),
('Ataleia', 13),
('Augusto de Lima', 13),
('Baependi', 13),
('Baldim', 13),
('Bambui', 13),
('Bandeira do Sul', 13),
('Bandeira', 13),
('Barao de Cocais', 13),
('Barao de Monte Alto', 13),
('Barbacena', 13),
('Barra Longa', 13),
('Barroso', 13),
('Bela Vista de Minas', 13),
('Belmiro Braga', 13),
('Belo Horizonte', 13),
('Belo Oriente', 13),
('Belo Vale', 13),
('Berilo', 13),
('Berizal', 13),
('Bertopolis', 13),
('Betim', 13),
('Bias Fortes', 13),
('Bicas', 13),
('Biquinhas', 13),
('Boa Esperanca', 13),
('Bocaina de Minas', 13),
('Bocaiuva', 13),
('Bom Despacho', 13),
('Bom Jardim de Minas', 13),
('Bom Jesus da Penha', 13),
('Bom Jesus do Amparo', 13),
('Bom Jesus do Galho', 13),
('Bom Repouso', 13),
('Bom Sucesso', 13),
('Bonfim', 13),
('Bonfinopolis de Minas', 13),
('Bonito de Minas', 13),
('Borda da Mata', 13),
('Botelhos', 13),
('Botumirim', 13),
('Bras Pires', 13),
('Brasilandia de Minas', 13),
('Brasilia de Minas', 13),
('Brasopolis', 13),
('Braunas', 13),
('Brumadinho', 13),
('Bueno Brandao', 13),
('Buenopolis', 13),
('Bugre', 13),
('Buritis', 13),
('Buritizeiro', 13),
('Cabeceira Grande', 13),
('Cabo Verde', 13),
('Cachoeira Dourada', 13),
('Cachoeira da Prata', 13),
('Cachoeira de Minas', 13),
('Cachoeira de Pajeu', 13),
('Caetanopolis', 13),
('Caete', 13),
('Caiana', 13),
('Cajuri', 13),
('Caldas', 13),
('Camacho', 13),
('Camanducaia', 13),
('Cambui', 13),
('Cambuquira', 13),
('Campanario', 13),
('Campanha', 13),
('Campestre', 13),
('Campina Verde', 13),
('Campo Azul', 13),
('Campo Belo', 13),
('Campo Florido', 13),
('Campo do Meio', 13),
('Campos Altos', 13),
('Campos Gerais', 13),
('Cana Verde', 13),
('Canaa', 13),
('Canapolis', 13),
('Candeias', 13),
('Cantagalo', 13),
('Caparao', 13),
('Capela Nova', 13),
('Capelinha', 13),
('Capetinga', 13),
('Capim Branco', 13),
('Capinopolis', 13),
('Capitao Andrade', 13),
('Capitao Eneas', 13),
('Capitolio', 13),
('Caputira', 13),
('Carai', 13),
('Caranaiba', 13),
('Carandai', 13),
('Carangola', 13),
('Caratinga', 13),
('Carbonita', 13),
('Careacu', 13),
('Carlos Chagas', 13),
('Carmesia', 13),
('Carmo da Cachoeira', 13),
('Carmo da Mata', 13),
('Carmo de Minas', 13),
('Carmo do Cajuru', 13),
('Carmo do Paranaiba', 13),
('Carmo do Rio Claro', 13),
('Carmopolis de Minas', 13),
('Carneirinho', 13),
('Carrancas', 13),
('Carvalhopolis', 13),
('Carvalhos', 13),
('Casa Grande', 13),
('Cascalho Rico', 13),
('Cassia', 13),
('Cataguases', 13),
('Catas Altas da Noruega', 13),
('Catas Altas', 13),
('Catuji', 13),
('Catuti', 13),
('Caxambu', 13),
('Cedro do Abaete', 13),
('Central de Minas', 13),
('Centralina', 13),
('Chacara', 13),
('Chale', 13),
('Chapada Gaucha', 13),
('Chapada do Norte', 13),
('Chiador', 13),
('Cipotanea', 13),
('Claraval', 13),
('Claro dos Pocoes', 13),
('Claudio', 13),
('Coimbra', 13),
('Coluna', 13),
('Comendador Gomes', 13),
('Comercinho', 13),
('Conceicao da Aparecida', 13),
('Conceicao da Barra de Minas', 13),
('Conceicao das Alagoas', 13),
('Conceicao das Pedras', 13),
('Conceicao de Ipanema', 13),
('Conceicao do Mato Dentro', 13),
('Conceicao do Para', 13),
('Conceicao do Rio Verde', 13),
('Conceicao dos Ouros', 13),
('Conego Marinho', 13),
('Confins', 13),
('Congonhal', 13),
('Congonhas do Norte', 13),
('Congonhas', 13),
('Conquista', 13),
('Conselheiro Lafaiete', 13),
('Conselheiro Pena', 13),
('Consolacao', 13),
('Contagem', 13),
('Coqueiral', 13),
('Coracao de Jesus', 13),
('Cordisburgo', 13),
('Cordislandia', 13),
('Corinto', 13),
('Coroaci', 13),
('Coromandel', 13),
('Coronel Fabriciano', 13),
('Coronel Murta', 13),
('Coronel Pacheco', 13),
('Coronel Xavier Chaves', 13),
('Corrego Danta', 13),
('Corrego Fundo', 13),
('Corrego Novo', 13),
('Corrego do Bom Jesus', 13),
('Couto de Magalhaes de Minas', 13),
('Crisolita', 13),
('Cristais', 13),
('Cristalia', 13),
('Cristiano Otoni', 13),
('Cristina', 13),
('Crucilandia', 13),
('Cruzeiro da Fortaleza', 13),
('Cruzilia', 13),
('Cuparaque', 13),
('Curral de Dentro', 13),
('Curvelo', 13),
('Datas', 13),
('Delfim Moreira', 13),
('Delfinopolis', 13),
('Delta', 13),
('Descoberto', 13),
('Desterro de Entre Rios', 13),
('Desterro do Melo', 13),
('Diamantina', 13),
('Diogo de Vasconcelos', 13),
('Dionisio', 13),
('Divinesia', 13),
('Divino das Laranjeiras', 13),
('Divino', 13),
('Divinolandia de Minas', 13),
('Divinopolis', 13),
('Divisa Alegre', 13),
('Divisa Nova', 13),
('Divisopolis', 13),
('Dom Bosco', 13),
('Dom Cavati', 13),
('Dom Joaquim', 13),
('Dom Silverio', 13),
('Dom Vicoso', 13),
('Dona Euzebia', 13),
('Dores de Campos', 13),
('Dores de Guanhaes', 13),
('Dores do Indaia', 13),
('Dores do Turvo', 13),
('Doresopolis', 13),
('Douradoquara', 13),
('Durande', 13),
('Eloi Mendes', 13),
('Engenheiro Caldas', 13),
('Engenheiro Navarro', 13),
('Entre Folhas', 13),
('Entre Rios de Minas', 13),
('Ervalia', 13),
('Esmeraldas', 13),
('Espera Feliz', 13),
('Espinosa', 13),
('Espirito Santo do Dourado', 13),
('Estiva', 13),
('Estrela Dalva', 13),
('Estrela do Indaia', 13),
('Estrela do Sul', 13),
('Eugenopolis', 13),
('Ewbank da Camara', 13),
('Extrema', 13),
('Fama', 13),
('Faria Lemos', 13),
('Felicio dos Santos', 13),
('Felisburgo', 13),
('Felixlandia', 13),
('Fernandes Tourinho', 13),
('Ferros', 13),
('Fervedouro', 13),
('Florestal', 13),
('Formiga', 13),
('Formoso', 13),
('Fortaleza de Minas', 13),
('Fortuna de Minas', 13),
('Francisco Badaro', 13),
('Francisco Dumont', 13),
('Francisco Sa', 13),
('Franciscopolis', 13),
('Frei Gaspar', 13),
('Frei Inocencio', 13),
('Frei Lagonegro', 13),
('Fronteira dos Vales', 13),
('Fronteira', 13),
('Fruta de Leite', 13),
('Frutal', 13),
('Funilandia', 13),
('Galileia', 13),
('Gameleiras', 13),
('Glaucilandia', 13),
('Goiabeira', 13),
('Goiana', 13),
('Goncalves', 13),
('Gonzaga', 13),
('Gouvea', 13),
('Governador Valadares', 13),
('Grao Mogol', 13),
('Grupiara', 13),
('Guanhaes', 13),
('Guape', 13),
('Guaraciaba', 13),
('Guaraciama', 13),
('Guaranesia', 13),
('Guarani', 13),
('Guarara', 13),
('Guarda-Mor', 13),
('Guaxupe', 13),
('Guidoval', 13),
('Guimarania', 13),
('Guiricema', 13),
('Gurinhata', 13),
('Heliodora', 13),
('Iapu', 13),
('Ibertioga', 13),
('Ibia', 13),
('Ibiai', 13),
('Ibiracatu', 13),
('Ibiraci', 13),
('Ibirite', 13),
('Ibitiura de Minas', 13),
('Ibituruna', 13),
('Icarai de Minas', 13),
('Igarape', 13),
('Igaratinga', 13),
('Iguatama', 13),
('Ijaci', 13),
('Ilicinea', 13),
('Imbe de Minas', 13),
('Inconfidentes', 13),
('Indaiabira', 13),
('Indianopolis', 13),
('Ingai', 13),
('Inhapim', 13),
('Inhauma', 13),
('Inimutaba', 13),
('Ipaba', 13),
('Ipanema', 13),
('Ipatinga', 13),
('Ipiacu', 13),
('Ipuiuna', 13),
('Irai de Minas', 13),
('Itabira', 13),
('Itabirinha de Mantena', 13),
('Itabirito', 13),
('Itacambira', 13),
('Itacarambi', 13),
('Itaguara', 13),
('Itaipe', 13),
('Itajuba', 13),
('Itamarandiba', 13),
('Itamarati de Minas', 13),
('Itambacuri', 13),
('Itambe do Mato Dentro', 13),
('Itamogi', 13),
('Itamonte', 13),
('Itanhandu', 13),
('Itanhomi', 13),
('Itaobim', 13),
('Itapagipe', 13),
('Itapecerica', 13),
('Itapeva', 13),
('Itatiaiucu', 13),
('Itau de Minas', 13),
('Itauna', 13),
('Itaverava', 13),
('Itinga', 13),
('Itueta', 13),
('Ituiutaba', 13),
('Itumirim', 13),
('Iturama', 13),
('Itutinga', 13),
('Jaboticatubas', 13),
('Jacinto', 13),
('Jacui', 13),
('Jacutinga', 13),
('Jaguaracu', 13),
('Jaiba', 13),
('Jampruca', 13),
('Janauba', 13),
('Januaria', 13),
('Japaraiba', 13),
('Japonvar', 13),
('Jeceaba', 13),
('Jenipapo de Minas', 13),
('Jequeri', 13),
('Jequitai', 13),
('Jequitiba', 13),
('Jequitinhonha', 13),
('Jesuania', 13),
('Joaima', 13),
('Joanesia', 13),
('Joao Monlevade', 13),
('Joao Pinheiro', 13),
('Joaquim Felicio', 13),
('Jordania', 13),
('Jose Goncalves de Minas', 13),
('Jose Raydan', 13),
('Josenopolis', 13),
('Juatuba', 13),
('Juiz de Fora', 13),
('Juramento', 13),
('Juruaia', 13),
('Juvenilia', 13),
('Ladainha', 13),
('Lagamar', 13),
('Lagoa Dourada', 13),
('Lagoa Formosa', 13),
('Lagoa Grande', 13),
('Lagoa Santa', 13),
('Lagoa da Prata', 13),
('Lagoa dos Patos', 13),
('Lagoas', 13),
('Lajinha', 13),
('Lambari', 13),
('Lamim', 13),
('Laranjal', 13),
('Lassance', 13),
('Lavras', 13),
('Leandro Ferreira', 13),
('Leme do Prado', 13),
('Leopoldina', 13),
('Liberdade', 13),
('Lima Duarte', 13),
('Limeira do Oeste', 13),
('Lontra', 13),
('Luisburgo', 13),
('Luislandia', 13),
('Luminarias', 13),
('Luz', 13),
('Machacalis', 13),
('Machado', 13),
('Madre de Deus de Minas', 13),
('Malacacheta', 13),
('Mamonas', 13),
('Manga', 13),
('Manhuacu', 13),
('Manhumirim', 13),
('Mantena', 13),
('Mar de Espanha', 13),
('Maravilhas', 13),
('Maria da Fe', 13),
('Mariana', 13),
('Marilac', 13),
('Mario Campos', 13),
('Maripa de Minas', 13),
('Marlieria', 13),
('Marmelopolis', 13),
('Martinho Campos', 13),
('Martins Soares', 13),
('Mata Verde', 13),
('Materlandia', 13),
('Mateus Leme', 13),
('Mathias Lobato', 13),
('Matias Barbosa', 13),
('Matias Cardoso', 13),
('Matipo', 13),
('Mato Verde', 13),
('Matozinhos', 13),
('Matutina', 13),
('Medeiros', 13),
('Medina', 13),
('Mendes Pimentel', 13),
('Merces', 13),
('Mesquita', 13),
('Minas Novas', 13),
('Minduri', 13),
('Mirabela', 13),
('Miradouro', 13),
('Mirai', 13),
('Miravania', 13),
('Moeda', 13),
('Moema', 13),
('Monjolos', 13),
('Monsenhor Paulo', 13),
('Montalvania', 13),
('Monte Alegre de Minas', 13),
('Monte Azul', 13),
('Monte Belo', 13),
('Monte Carmelo', 13),
('Monte Formoso', 13),
('Monte Santo de Minas', 13),
('Monte Siao', 13),
('Montes Claros', 13),
('Montezuma', 13),
('Morada Nova de Minas', 13),
('Morro da Garca', 13),
('Morro do Pilar', 13),
('Munhoz', 13),
('Muriae', 13),
('Mutum', 13),
('Muzambinho', 13),
('Nacip Raydan', 13),
('Nanuque', 13),
('Naque', 13),
('Natalandia', 13),
('Natercia', 13),
('Nazareno', 13),
('Nepomuceno', 13),
('Ninheira', 13),
('Nova Belem', 13),
('Nova Era', 13),
('Nova Lima', 13),
('Nova Modica', 13),
('Nova Ponte', 13),
('Nova Porteirinha', 13),
('Nova Resende', 13),
('Nova Serrana', 13),
('Nova Uniao', 13),
('Novo Cruzeiro', 13),
('Novo Oriente de Minas', 13),
('Novorizonte', 13),
('Olaria', 13),
('Olhos-d\'Agua', 13),
('Olimpio Noronha', 13),
('Oliveira Fortes', 13),
('Oliveira', 13),
('Onca de Pitangui', 13),
('Oratorios', 13),
('Orizania', 13),
('Ouro Branco', 13),
('Ouro Fino', 13),
('Ouro Preto', 13),
('Ouro Verde de Minas', 13),
('Padre Carvalho', 13),
('Padre Paraiso', 13),
('Pai Pedro', 13),
('Paineiras', 13),
('Pains', 13),
('Paiva', 13),
('Palma', 13),
('Palmopolis', 13),
('Papagaios', 13),
('Para de Minas', 13),
('Paracatu', 13),
('Paraguacu', 13),
('Paraisopolis', 13),
('Paraopeba', 13),
('Passa Quatro', 13),
('Passa Tempo', 13),
('Passa Vinte', 13),
('Passabem', 13),
('Passos', 13),
('Patis', 13),
('Patos de Minas', 13),
('Patrocinio do Muriae', 13),
('Patrocinio', 13),
('Paula Candido', 13),
('Paulistas', 13),
('Pavao', 13),
('Pecanha', 13),
('Pedra Azul', 13),
('Pedra Bonita', 13),
('Pedra Dourada', 13),
('Pedra do Anta', 13),
('Pedra do Indaia', 13),
('Pedralva', 13),
('Pedras de Maria da Cruz', 13),
('Pedrinopolis', 13),
('Pedro Leopoldo', 13),
('Pedro Teixeira', 13),
('Pequeri', 13),
('Pequi', 13),
('Perdigao', 13),
('Perdizes', 13),
('Perdoes', 13),
('Periquito', 13),
('Pescador', 13),
('Piau', 13),
('Piedade de Caratinga', 13),
('Piedade de Ponte Nova', 13),
('Piedade do Rio Grande', 13),
('Piedade dos Gerais', 13),
('Pimenta', 13),
('Pingo d\'Agua', 13),
('Pintopolis', 13),
('Piracema', 13),
('Pirajuba', 13),
('Piranga', 13),
('Pirangucu', 13),
('Piranguinho', 13),
('Pirapetinga', 13),
('Pirapora', 13),
('Pirauba', 13),
('Pitangui', 13),
('Piui', 13),
('Planura', 13),
('Poco Fundo', 13),
('Pocos de Caldas', 13),
('Pocrane', 13),
('Pompeu', 13),
('Ponte Nova', 13),
('Ponto Chique', 13),
('Ponto dos Volantes', 13),
('Porteirinha', 13),
('Porto Firme', 13),
('Pote', 13),
('Pouso Alegre', 13),
('Pouso Alto', 13),
('Prados', 13),
('Prata', 13),
('Pratapolis', 13),
('Pratinha', 13),
('Presidente Bernardes', 13),
('Presidente Juscelino', 13),
('Presidente Kubitschek', 13),
('Presidente Olegario', 13),
('Prudente de Morais', 13),
('Quartel Geral', 13),
('Queluzita', 13),
('Raposos', 13),
('Raul Soares', 13),
('Recreio', 13),
('Reduto', 13),
('Resende Costa', 13),
('Resplendor', 13),
('Ressaquinha', 13),
('Riachinho', 13),
('Riacho dos Machados', 13),
('Ribeirao Vermelho', 13),
('Ribeirao das Neves', 13),
('Rio Acima', 13),
('Rio Casca', 13),
('Rio Doce', 13),
('Rio Espera', 13),
('Rio Manso', 13),
('Rio Novo', 13),
('Rio Paranaiba', 13),
('Rio Pardo de Minas', 13),
('Rio Piracicaba', 13),
('Rio Pomba', 13),
('Rio Preto', 13),
('Rio Vermelho', 13),
('Rio do Prado', 13),
('Ritapolis', 13),
('Rochedo de Minas', 13),
('Rodeiro', 13),
('Romaria', 13),
('Rosario da Limeira', 13),
('Rubelita', 13),
('Rubim', 13),
('Sabara', 13),
('Sabinopolis', 13),
('Sacramento', 13),
('Salinas', 13),
('Salto da Divisa', 13),
('Santa Barbara do Leste', 13),
('Santa Barbara do Monte Verde', 13),
('Santa Barbara do Tugurio', 13),
('Santa Barbara', 13),
('Santa Cruz de Minas', 13),
('Santa Cruz de Salinas', 13),
('Santa Cruz do Escalvado', 13),
('Santa Efigenia de Minas', 13),
('Santa Fe de Minas', 13),
('Santa Helena de Minas', 13),
('Santa Juliana', 13),
('Santa Luzia', 13),
('Santa Margarida', 13),
('Santa Maria de Itabira', 13),
('Santa Maria do Salto', 13),
('Santa Maria do Suacui', 13),
('Santa Rita de Caldas', 13),
('Santa Rita de Ibitipoca', 13),
('Santa Rita de Jacutinga', 13),
('Santa Rita de Minas', 13),
('Santa Rita do Itueto', 13),
('Santa Rita do Sapucai', 13),
('Santa Rosa da Serra', 13),
('Santa Vitoria', 13),
('Santana da Vargem', 13),
('Santana de Cataguases', 13),
('Santana de Pirapama', 13),
('Santana do Deserto', 13),
('Santana do Garambeu', 13),
('Santana do Jacare', 13),
('Santana do Manhuacu', 13),
('Santana do Paraiso', 13),
('Santana do Riacho', 13),
('Santana dos Montes', 13),
('Santo Antonio do Amparo', 13),
('Santo Antonio do Aventureiro', 13),
('Santo Antonio do Grama', 13),
('Santo Antonio do Itambe', 13),
('Santo Antonio do Jacinto', 13),
('Santo Antonio do Monte', 13),
('Santo Antonio do Retiro', 13),
('Santo Antonio do Rio Abaixo', 13),
('Santo Hipolito', 13),
('Santos Dumont', 13),
('Sao Bento Abade', 13),
('Sao Bras do Suacui', 13),
('Sao Domingos das Dores', 13),
('Sao Domingos do Prata', 13),
('Sao Felix de Minas', 13),
('Sao Francisco de Paula', 13),
('Sao Francisco de Sales', 13),
('Sao Francisco do Gloria', 13),
('Sao Francisco', 13),
('Sao Geraldo da Piedade', 13),
('Sao Geraldo do Baixio', 13),
('Sao Geraldo', 13),
('Sao Goncalo do Abaete', 13),
('Sao Goncalo do Para', 13),
('Sao Goncalo do Rio Abaixo', 13),
('Sao Goncalo do Rio Preto', 13),
('Sao Goncalo do Sapucai', 13),
('Sao Gotardo', 13),
('Sao Joao Batista do Gloria', 13),
('Sao Joao Evangelista', 13),
('Sao Joao Nepomuceno', 13),
('Sao Joao da Lagoa', 13),
('Sao Joao da Mata', 13),
('Sao Joao da Ponte', 13),
('Sao Joao das Missoes', 13),
('Sao Joao del Rei', 13),
('Sao Joao do Manhuacu', 13),
('Sao Joao do Manteninha', 13),
('Sao Joao do Oriente', 13),
('Sao Joao do Pacui', 13),
('Sao Joao do Paraiso', 13),
('Sao Joaquim de Bicas', 13),
('Sao Jose da Barra', 13),
('Sao Jose da Lapa', 13),
('Sao Jose da Safira', 13),
('Sao Jose da Varginha', 13),
('Sao Jose do Alegre', 13),
('Sao Jose do Divino', 13),
('Sao Jose do Goiabal', 13),
('Sao Jose do Jacuri', 13),
('Sao Jose do Mantimento', 13),
('Sao Lourenco', 13),
('Sao Miguel do Anta', 13),
('Sao Pedro da Uniao', 13),
('Sao Pedro do Suacui', 13),
('Sao Pedro dos Ferros', 13),
('Sao Romao', 13),
('Sao Roque de Minas', 13),
('Sao Sebastiao da Bela Vista', 13),
('Sao Sebastiao da Vargem Alegre', 13),
('Sao Sebastiao do Anta', 13),
('Sao Sebastiao do Maranhao', 13),
('Sao Sebastiao do Oeste', 13),
('Sao Sebastiao do Paraiso', 13),
('Sao Sebastiao do Rio Preto', 13),
('Sao Sebastiao do Rio Verde', 13),
('Sao Thome das Letras', 13),
('Sao Tiago', 13),
('Sao Tomas de Aquino', 13),
('Sao Vicente de Minas', 13),
('Sapucai-Mirim', 13),
('Sardoa', 13),
('Sarzedo', 13),
('Sem-Peixe', 13),
('Senador Amaral', 13),
('Senador Cortes', 13),
('Senador Firmino', 13),
('Senador Jose Bento', 13),
('Senador Modestino Goncalves', 13),
('Senhora de Oliveira', 13),
('Senhora do Porto', 13),
('Senhora dos Remedios', 13),
('Sericita', 13),
('Seritinga', 13),
('Serra Azul de Minas', 13),
('Serra da Saudade', 13),
('Serra do Salitre', 13),
('Serra dos Aimores', 13),
('Serrania', 13),
('Serranopolis de Minas', 13),
('Serranos', 13),
('Serro', 13),
('Sete Lagoas', 13),
('Setubinha', 13),
('Silveirania', 13),
('Silvianopolis', 13),
('Simao Pereira', 13),
('Simonesia', 13),
('Sobralia', 13),
('Soledade de Minas', 13),
('Tabuleiro', 13),
('Taiobeiras', 13),
('Taparuba', 13),
('Tapira', 13),
('Tapirai', 13),
('Taquaracu de Minas', 13),
('Tarumirim', 13),
('Teixeiras', 13),
('Teofilo Otoni', 13),
('Timoteo', 13),
('Tiradentes', 13),
('Tiros', 13),
('Tocantins', 13),
('Tocos do Moji', 13),
('Toledo', 13),
('Tombos', 13),
('Tres Coracoes', 13),
('Tres Marias', 13),
('Tres Pontas', 13),
('Tumiritinga', 13),
('Tupaciguara', 13),
('Turmalina', 13),
('Turvolandia', 13),
('Uba', 13),
('Ubai', 13),
('Ubaporanga', 13),
('Uberaba', 13),
('Uberlandia', 13),
('Umburatiba', 13),
('Unai', 13),
('Uniao de Minas', 13),
('Uruana de Minas', 13),
('Urucania', 13),
('Urucuia', 13),
('Vargem Alegre', 13),
('Vargem Bonita', 13),
('Vargem Grande do Rio Pardo', 13),
('Varginha', 13),
('Varjao de MInas', 13),
('Varzea da Palma', 13),
('Varzelandia', 13),
('Vazante', 13),
('Verdelandia', 13),
('Veredinha', 13),
('Verissimo', 13),
('Vermelho Novo', 13),
('Vespasiano', 13),
('Vicosa', 13),
('Vieiras', 13),
('Virgem da Lapa', 13),
('Virginia', 13),
('Virginopolis', 13),
('Virgolandia', 13),
('Visconde do Rio Branco', 13),
('Volta Grande', 13),
('Wenceslau Braz', 13);