INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Angra dos Reis', 19),
('Aperibe', 19),
('Araruama', 19),
('Areal', 19),
('Armacao de Buzios', 19),
('Arraial do Cabo', 19),
('Barra Mansa', 19),
('Barra do Pirai', 19),
('Belford Roxo', 19),
('Bom Jardim', 19),
('Bom Jesus do Itabapoana', 19),
('Cabo Frio', 19),
('Cachoeiras de Macacu', 19),
('Cambuci', 19),
('Campos dos Goytacazes', 19),
('Cantagalo', 19),
('Carapebus', 19),
('Cardoso Moreira', 19),
('Carmo', 19),
('Casimiro de Abreu', 19),
('Comendador Levy Gasparian', 19),
('Conceicao de Macabu', 19),
('Cordeiro', 19),
('Duas Barras', 19),
('Duque de Caxias', 19),
('Engenheiro Paulo de Frontin', 19),
('Guapimirim', 19),
('Iguaba Grande', 19),
('Itaborai', 19),
('Itaguai', 19),
('Italva', 19),
('Itaocara', 19),
('Itaperuna', 19),
('Itatiaia', 19),
('Japeri', 19),
('Laje do Muriae', 19),
('Macae', 19),
('Macuco', 19),
('Mage', 19),
('Mangaratiba', 19),
('Marica', 19),
('Mendes', 19),
('Miguel Pereira', 19),
('Miracema', 19),
('Natividade', 19),
('Nilopolis', 19),
('Niteroi', 19),
('Nova Friburgo', 19),
('Nova Iguacu', 19),
('Paracambi', 19),
('Paraiba do Sul', 19),
('Parati', 19),
('Paty do Alferes', 19),
('Petropolis', 19),
('Pinheiral', 19),
('Pirai', 19),
('Porciuncula', 19),
('Porto Real', 19),
('Quatis', 19),
('Queimados', 19),
('Quissama', 19),
('Resende', 19),
('Rio Bonito', 19),
('Rio Claro', 19),
('Rio das Flores', 19),
('Rio das Ostras', 19),
('Rio de Janeiro', 19),
('Santa Maria Madalena', 19),
('Santo Antonio de Padua', 19),
('Sao Fidelis', 19),
('Sao Francisco de Itabapoana', 19),
('Sao Goncalo', 19),
('Sao Joao da Barra', 19),
('Sao Joao de Meriti', 19),
('Sao Jose de Uba', 19),
('Sao Jose do Vale do Rio Preto', 19),
('Sao Pedro da Aldeia', 19),
('Sao Sebastiao do Alto', 19),
('Sapucaia', 19),
('Saquarema', 19),
('Seropedica', 19),
('Silva Jardim', 19),
('Sumidouro', 19),
('Tangua', 19),
('Teresopolis', 19),
('Trajano de Morais', 19),
('Tres Rios', 19),
('Valenca', 19),
('Varre-Sai', 19),
('Vassouras', 19),
('Volta Redonda', 19);