INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Amparo de Sao Francisco', 26),
('Aquidaba', 26),
('Aracaju', 26),
('Araua', 26),
('Areia Branca', 26),
('Barra dos Coqueiros', 26),
('Boquim', 26),
('Brejo Grande', 26),
('Campo do Brito', 26),
('Canhoba', 26),
('Caninde de Sao Francisco', 26),
('Capela', 26),
('Carira', 26),
('Carmopolis', 26),
('Cedro de Sao Joao', 26),
('Cristinapolis', 26),
('Cumbe', 26),
('Divina Pastora', 26),
('Estancia', 26),
('Feira Nova', 26),
('Frei Paulo', 26),
('Gararu', 26),
('General Maynard', 26),
('Gracho Cardoso', 26),
('Ilha das Flores', 26),
('Indiaroba', 26),
('Itabaiana', 26),
('Itabaianinha', 26),
('Itabi', 26),
('Itaporanga d\'Ajuda', 26),
('Japaratuba', 26),
('Japoata', 26),
('Lagarto', 26),
('Laranjeiras', 26),
('Macambira', 26),
('Malhada dos Bois', 26),
('Malhador', 26),
('Maruim', 26),
('Moita Bonita', 26),
('Monte Alegre de Sergipe', 26),
('Muribeca', 26),
('Neopolis', 26),
('Nossa Senhora Aparecida', 26),
('Nossa Senhora da Gloria', 26),
('Nossa Senhora das Dores', 26),
('Nossa Senhora de Lourdes', 26),
('Nossa Senhora do Socorro', 26),
('Pacatuba', 26),
('Pedra Mole', 26),
('Pedrinhas', 26),
('Pinhao', 26),
('Pirambu', 26),
('Poco Redondo', 26),
('Poco Verde', 26),
('Porto da Folha', 26),
('Propria', 26),
('Riachao do Dantas', 26),
('Riachuelo', 26),
('Ribeiropolis', 26),
('Rosario do Catete', 26),
('Salgado', 26),
('Santa Luzia do Itanhy', 26),
('Santa Rosa de Lima', 26),
('Santana do Sao Francisco', 26),
('Santo Amaro das Brotas', 26),
('Sao Cristovao', 26),
('Sao Domingos', 26),
('Sao Francisco', 26),
('Sao Miguel do Aleixo', 26),
('Simao Dias', 26),
('Siriri', 26),
('Telha', 26),
('Tobias Barreto', 26),
('Tomar do Geru', 26),
('Umbauba', 26);