INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abdon Batista', 24),
('Abelardo Luz', 24),
('Agrolandia', 24),
('Agronomica', 24),
('Agua Doce', 24),
('Aguas Frias', 24),
('Aguas Mornas', 24),
('Aguas de Chapeco', 24),
('Alfredo Wagner', 24),
('Alto Bela Vista', 24),
('Anchieta', 24),
('Angelina', 24),
('Anita Garibaldi', 24),
('Anitapolis', 24),
('Antonio Carlos', 24),
('Apiuna', 24),
('Arabuta', 24),
('Araquari', 24),
('Ararangua', 24),
('Armazem', 24),
('Arroio Trinta', 24),
('Arvoredo', 24),
('Ascurra', 24),
('Atalanta', 24),
('Aurora', 24),
('Balneario Arroio do Silva', 24),
('Balneario Barra do Sul', 24),
('Balneario Camboriu', 24),
('Balneario Gaivota', 24),
('Bandeirante', 24),
('Barra Bonita', 24),
('Barra Velha', 24),
('Bela Vista do Toldo', 24),
('Belmonte', 24),
('Benedito Novo', 24),
('Biguacu', 24),
('Blumenau', 24),
('Bocaina do Sul', 24),
('Bom Jardim da Serra', 24),
('Bom Jesus do Oeste', 24),
('Bom Jesus', 24),
('Bom Retiro', 24),
('Bombinhas', 24),
('Botuvera', 24),
('Braco do Norte', 24),
('Braco do Trombudo', 24),
('Brunopolis', 24),
('Brusque', 24),
('Cacador', 24),
('Caibi', 24),
('Calmon', 24),
('Camboriu', 24),
('Campo Alegre', 24),
('Campo Belo do Sul', 24),
('Campo Ere', 24),
('Campos Novos', 24),
('Canelinha', 24),
('Canoinhas', 24),
('Capao Alto', 24),
('Capinzal', 24),
('Capivari de Baixo', 24),
('Catanduvas', 24),
('Caxambu do Sul', 24),
('Celso Ramos', 24),
('Cerro Negro', 24),
('Chapadao do Lageado', 24),
('Chapeco', 24),
('Cocal do Sul', 24),
('Concordia', 24),
('Cordilheira Alta', 24),
('Coronel Freitas', 24),
('Coronel Martins', 24),
('Correia Pinto', 24),
('Corupa', 24),
('Criciuma', 24),
('Cunha Pora', 24),
('Cunhatai', 24),
('Curitibanos', 24),
('Descanso', 24),
('Dionisio Cerqueira', 24),
('Dona Emma', 24),
('Doutor Pedrinho', 24),
('Entre Rios', 24),
('Ermo', 24),
('Erval Velho', 24),
('Faxinal dos Guedes', 24),
('Flor do Sertao', 24),
('Florianopolis', 24),
('Formosa do Sul', 24),
('Forquilhinha', 24),
('Fraiburgo', 24),
('Frei Rogerio', 24),
('Galvao', 24),
('Garopaba', 24),
('Garuva', 24),
('Gaspar', 24),
('Governador Celso Ramos', 24),
('Grao Para', 24),
('Gravatal', 24),
('Guabiruba', 24),
('Guaraciaba', 24),
('Guaramirim', 24),
('Guaruja do Sul', 24),
('Guatambu', 24),
('Herval d\'Oeste', 24),
('Ibiam', 24),
('Ibicare', 24),
('Ibirama', 24),
('Icara', 24),
('Ilhota', 24),
('Imarui', 24),
('Imbituba', 24),
('Imbuia', 24),
('Indaial', 24),
('Iomere', 24),
('Ipira', 24),
('Ipora do Oeste', 24),
('Ipuacu', 24),
('Ipumirim', 24),
('Iraceminha', 24),
('Irani', 24),
('Irati', 24),
('Irineopolis', 24),
('Ita', 24),
('Itaiopolis', 24),
('Itajai', 24),
('Itapema', 24),
('Itapiranga', 24),
('Itapoa', 24),
('Ituporanga', 24),
('Jabora', 24),
('Jacinto Machado', 24),
('Jaguaruna', 24),
('Jaragua do Sul', 24),
('Jardinopolis', 24),
('Joacaba', 24),
('Joinville', 24),
('Jose Boiteux', 24),
('Jupia', 24),
('Lacerdopolis', 24),
('Lages', 24),
('Laguna', 24),
('Lajeado Grande', 24),
('Laurentino', 24),
('Lauro Muller', 24),
('Lebon Regis', 24),
('Leoberto Leal', 24),
('Lindoia do Sul', 24),
('Lontras', 24),
('Luiz Alves', 24),
('Luzerna', 24),
('Macieira', 24),
('Mafra', 24),
('Major Gercino', 24),
('Major Vieira', 24),
('Maracaja', 24),
('Maravilha', 24),
('Marema', 24),
('Massaranduba', 24),
('Matos Costa', 24),
('Meleiro', 24),
('Mirim Doce', 24),
('Modelo', 24),
('Mondai', 24),
('Monte Carlo', 24),
('Monte Castelo', 24),
('Morro Grande', 24),
('Morro da Fumaca', 24),
('Navegantes', 24),
('Nova Erechim', 24),
('Nova Itaberaba', 24),
('Nova Trento', 24),
('Nova Veneza', 24),
('Novo Horizonte', 24),
('Orleans', 24),
('Otacilio Costa', 24),
('Ouro Verde', 24),
('Ouro', 24),
('Paial', 24),
('Painel', 24),
('Palhoca', 24),
('Palma Sola', 24),
('Palmeira', 24),
('Palmitos', 24),
('Papanduva', 24),
('Paraiso', 24),
('Passo de Torres', 24),
('Passos Maia', 24),
('Paulo Lopes', 24),
('Pedras Grandes', 24),
('Penha', 24),
('Peritiba', 24),
('Petrolandia', 24),
('Picarras', 24),
('Pinhalzinho', 24),
('Pinheiro Preto', 24),
('Piratuba', 24),
('Planalto Alegre', 24),
('Pomerode', 24),
('Ponte Alta do Norte', 24),
('Ponte Alta', 24),
('Ponte Serrada', 24),
('Porto Belo', 24),
('Porto Uniao', 24),
('Pouso Redondo', 24),
('Praia Grande', 24),
('Presidente Castelo Branco', 24),
('Presidente Getulio', 24),
('Presidente Nereu', 24),
('Princesa', 24),
('Quilombo', 24),
('Rancho Queimado', 24),
('Rio Fortuna', 24),
('Rio Negrinho', 24),
('Rio Rufino', 24),
('Rio d\'Oeste', 24),
('Rio das Antas', 24),
('Rio do Campo', 24),
('Rio do Sul', 24),
('Rio dos Cedros', 24),
('Riqueza', 24),
('Rodeio', 24),
('Romelandia', 24),
('Salete', 24),
('Saltinho', 24),
('Salto Veloso', 24),
('Sangao', 24),
('Santa Cecilia', 24),
('Santa Helena', 24),
('Santa Rosa de Lima', 24),
('Santa Rosa do Sul', 24),
('Santa Terezinha do Progresso', 24),
('Santa Terezinha', 24),
('Santiago do Sul', 24),
('Santo Amaro da Imperatriz', 24),
('Sao Bento do Sul', 24),
('Sao Bernardino', 24),
('Sao Bonifacio', 24),
('Sao Carlos', 24),
('Sao Cristovao do Sul', 24),
('Sao Domingos', 24),
('Sao Francisco do Sul', 24),
('Sao Joao Batista', 24),
('Sao Joao do Itaperiu', 24),
('Sao Joao do Oeste', 24),
('Sao Joao do Sul', 24),
('Sao Joaquim', 24),
('Sao Jose do Cedro', 24),
('Sao Jose do Cerrito', 24),
('Sao Jose', 24),
('Sao Lourenco d\'Oeste', 24),
('Sao Ludgero', 24),
('Sao Martinho', 24),
('Sao Miguel d\'Oeste', 24),
('Sao Miguel da Boa Vista', 24),
('Sao Pedro de Alcantara', 24),
('Saudades', 24),
('Schroeder', 24),
('Seara', 24),
('Serra Alta', 24),
('Sideropolis', 24),
('Sombrio', 24),
('Sul Brasil', 24),
('Taio', 24),
('Tangara', 24),
('Tigrinhos', 24),
('Tijucas', 24),
('Timbe do Sul', 24),
('Timbo Grande', 24),
('Timbo', 24),
('Tres Barras', 24),
('Treviso', 24),
('Treze Tilias', 24),
('Treze de Maio', 24),
('Trombudo Central', 24),
('Tubarao', 24),
('Tunapolis', 24),
('Turvo', 24),
('Uniao do Oeste', 24),
('Urubici', 24),
('Urupema', 24),
('Urussanga', 24),
('Vargeao', 24),
('Vargem Bonita', 24),
('Vargem', 24),
('Vidal Ramos', 24),
('Videira', 24),
('Vitor Meireles', 24),
('Witmarsum', 24),
('Xanxere', 24),
('Xavantina', 24),
('Xaxim', 24),
('Zortea', 24);