INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Acaua', 18),
('Agricolandia', 18),
('Agua Branca', 18),
('Alagoinha do Piaui', 18),
('Alegrete do Piaui', 18),
('Alto Longa', 18),
('Altos', 18),
('Alvorada do Gurgueia', 18),
('Amarante', 18),
('Angical do Piaui', 18),
('Anisio de Abreu', 18),
('Antonio Almeida', 18),
('Aroazes', 18),
('Arraial', 18),
('Assuncao do Piaui', 18),
('Avelino Lopes', 18),
('Baixa Grande do Ribeiro', 18),
('Barra d\'Alcantara', 18),
('Barras', 18),
('Barreiras do Piaui', 18),
('Barro Duro', 18),
('Batalha', 18),
('Bela Vista do Piaui', 18),
('Belem do Piaui', 18),
('Beneditinos', 18),
('Bertolinia', 18),
('Betania do Piaui', 18),
('Boa Hora', 18),
('Bocaina', 18),
('Bom Jesus', 18),
('Bom Principio do Piaui', 18),
('Bonfim do Piaui', 18),
('Boqueirao do Piaui', 18),
('Brasileira', 18),
('Brejo do Piaui', 18),
('Buriti dos Lopes', 18),
('Buriti dos Montes', 18),
('Cabeceiras do Piaui', 18),
('Cajazeiras do Piaui', 18),
('Cajueiro da Praia', 18),
('Caldeirao Grande do Piaui', 18),
('Campinas do Piaui', 18),
('Campo Alegre do Fidalgo', 18),
('Campo Grande do Piaui', 18),
('Campo Largo do Piaui', 18),
('Campo Maior', 18),
('Canavieira', 18),
('Canto do Buriti', 18),
('Capitao Gervasio Oliveira', 18),
('Capitao de Campos', 18),
('Caracol', 18),
('Caraubas do Piaui', 18),
('Caridade do Piaui', 18),
('Castelo do Piaui', 18),
('Caxingo', 18),
('Cocal de Telha', 18),
('Cocal dos Alves', 18),
('Cocal', 18),
('Coivaras', 18),
('Colonia do Gurgueia', 18),
('Colonia do Piaui', 18),
('Conceicao do Caninde', 18),
('Coronel Jose Dias', 18),
('Corrente', 18),
('Cristalandia do Piaui', 18),
('Cristino Castro', 18),
('Curimata', 18),
('Currais', 18),
('Curral Novo do Piaui', 18),
('Curralinhos', 18),
('Demerval Lobao', 18),
('Dirceu Arcoverde', 18),
('Dom Expedito Lopes', 18),
('Dom Inocencio', 18),
('Domingos Mourao', 18),
('Elesbao Veloso', 18),
('Eliseu Martins', 18),
('Esperantina', 18),
('Fartura do Piaui', 18),
('Flores do Piaui', 18),
('Floresta do Piaui', 18),
('Floriano', 18),
('Francinopolis', 18),
('Francisco Ayres', 18),
('Francisco Macedo', 18),
('Francisco Santos', 18),
('Fronteiras', 18),
('Geminiano', 18),
('Gilbues', 18),
('Guadalupe', 18),
('Guaribas', 18),
('Hugo Napoleao', 18),
('Ilha Grande', 18),
('Inhuma', 18),
('Ipiranga do Piaui', 18),
('Isaias Coelho', 18),
('Itainopolis', 18),
('Itaueira', 18),
('Jacobina do Piaui', 18),
('Jaicos', 18),
('Jardim do Mulato', 18),
('Jatoba do Piaui', 18),
('Jerumenha', 18),
('Joao Costa', 18),
('Joaquim Pires', 18),
('Joca Marques', 18),
('Jose de Freitas', 18),
('Juazeiro do Piaui', 18),
('Julio Borges', 18),
('Jurema', 18),
('Lagoa Alegre', 18),
('Lagoa de Sao Francisco', 18),
('Lagoa do Barro do Piaui', 18),
('Lagoa do Piaui', 18),
('Lagoa do Sitio', 18),
('Lagoinha do Piaui', 18),
('Landri Sales', 18),
('Luis Correia', 18),
('Luzilandia', 18),
('Madeiro', 18),
('Manoel Emidio', 18),
('Marcolandia', 18),
('Marcos Parente', 18),
('Massape do Piaui', 18),
('Matias Olimpio', 18),
('Miguel Alves', 18),
('Miguel Leao', 18),
('Milton Brandao', 18),
('Monsenhor Gil', 18),
('Monsenhor Hipolito', 18),
('Monte Alegre do Piaui', 18),
('Morro Cabeca no Tempo', 18),
('Morro do Chapeu do Piaui', 18),
('Murici dos Portelas', 18),
('Nazare do Piaui', 18),
('Nossa Senhora de Nazare', 18),
('Nossa Senhora dos Remedios', 18),
('Nova Santa Rita', 18),
('Novo Oriente do Piaui', 18),
('Novo Santo Antonio', 18),
('Oeiras', 18),
('Olho d\'Agua do Piaui', 18),
('Padre Marcos', 18),
('Paes Landim', 18),
('Pajeu do Piaui', 18),
('Palmeira do Piaui', 18),
('Palmeirais', 18),
('Paqueta', 18),
('Parnagua', 18),
('Parnaiba', 18),
('Passagem Franca do Piaui', 18),
('Patos do Piaui', 18),
('Paulistana', 18),
('Pavussu', 18),
('Pedro II', 18),
('Pedro Laurentino', 18),
('Picos', 18),
('Pimenteiras', 18),
('Pio IX', 18),
('Piracuruca', 18),
('Piripiri', 18),
('Porto Alegre do Piaui', 18),
('Porto', 18),
('Prata do Piaui', 18),
('Queimada Nova', 18),
('Redencao do Gurgueia', 18),
('Regeneracao', 18),
('Riacho Frio', 18),
('Ribeira do Piaui', 18),
('Ribeiro Goncalves', 18),
('Rio Grande do Piaui', 18),
('Santa Cruz do Piaui', 18),
('Santa Cruz dos Milagres', 18),
('Santa Filomena', 18),
('Santa Luz', 18),
('Santa Rosa do Piaui', 18),
('Santana do Piaui', 18),
('Santo Antonio de Lisboa', 18),
('Santo Antonio dos Milagres', 18),
('Santo Inacio do Piaui', 18),
('Sao Braz do Piaui', 18),
('Sao Felix do Piaui', 18),
('Sao Francisco de Assis do Piaui', 18),
('Sao Francisco do Piaui', 18),
('Sao Goncalo do Gurgueia', 18),
('Sao Goncalo do Piaui', 18),
('Sao Joao da Canabrava', 18),
('Sao Joao da Fronteira', 18),
('Sao Joao da Serra', 18),
('Sao Joao da Varjota', 18),
('Sao Joao do Arraial', 18),
('Sao Joao do Piaui', 18),
('Sao Jose do Divino', 18),
('Sao Jose do Peixe', 18),
('Sao Jose do Piaui', 18),
('Sao Juliao', 18),
('Sao Lourenco do Piaui', 18),
('Sao Luis do Piaui', 18),
('Sao Miguel da Baixa Grande', 18),
('Sao Miguel do Fidalgo', 18),
('Sao Miguel do Tapuio', 18),
('Sao Pedro do Piaui', 18),
('Sao Raimundo Nonato', 18),
('Sebastiao Barros', 18),
('Sebastiao Leal', 18),
('Sigefredo Pacheco', 18),
('Simoes', 18),
('Simplicio Mendes', 18),
('Socorro do Piaui', 18),
('Sussuapara', 18),
('Tamboril do Piaui', 18),
('Tanque do Piaui', 18),
('Teresina', 18),
('Uniao', 18),
('Urucui', 18),
('Valenca do Piaui', 18),
('Varzea Branca', 18),
('Varzea Grande', 18),
('Vera Mendes', 18),
('Vila Nova do Piaui', 18),
('Wall Ferraz', 18);