INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Agua Clara', 12),
('Alcinopolis', 12),
('Amambai', 12),
('Anastacio', 12),
('Anaurilandia', 12),
('Angelica', 12),
('Antonio Joao', 12),
('Aparecida do Taboado', 12),
('Aquidauana', 12),
('Aral Moreira', 12),
('Bandeirantes', 12),
('Bataguassu', 12),
('Bataipora', 12),
('Bela Vista', 12),
('Bodoquena', 12),
('Bonito', 12),
('Brasilandia', 12),
('Caarapo', 12),
('Camapua', 12),
('Campo Grande', 12),
('Caracol', 12),
('Cassilandia', 12),
('Chapadao do Sul', 12),
('Corguinho', 12),
('Coronel Sapucaia', 12),
('Corumba', 12),
('Costa Rica', 12),
('Coxim', 12),
('Deodapolis', 12),
('Dois Irmaos do Buriti', 12),
('Douradina', 12),
('Dourados', 12),
('Eldorado', 12),
('Fatima do Sul', 12),
('Gloria de Dourados', 12),
('Guia Lopes da Laguna', 12),
('Iguatemi', 12),
('Inocencia', 12),
('Itapora', 12),
('Itaquirai', 12),
('Ivinhema', 12),
('Japora', 12),
('Jaraguari', 12),
('Jardim', 12),
('Jatei', 12),
('Juti', 12),
('Ladario', 12),
('Laguna Carapa', 12),
('Maracaju', 12),
('Miranda', 12),
('Mundo Novo', 12),
('Navirai', 12),
('Nioaque', 12),
('Nova Alvorada do Sul', 12),
('Nova Andradina', 12),
('Novo Horizonte do Sul', 12),
('Paranaiba', 12),
('Paranhos', 12),
('Pedro Gomes', 12),
('Ponta Pora', 12),
('Porto Murtinho', 12),
('Ribas do Rio Pardo', 12),
('Rio Brilhante', 12),
('Rio Negro', 12),
('Rio Verde de Mato Grosso', 12),
('Rochedo', 12),
('Santa Rita do Pardo', 12),
('Sao Gabriel do Oeste', 12),
('Selviria', 12),
('Sete Quedas', 12),
('Sidrolandia', 12),
('Sonora', 12),
('Tacuru', 12),
('Taquarussu', 12),
('Terenos', 12),
('Tres Lagoas', 12),
('Vicentina', 12);