INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Acorizal', 11),
('Agua Boa', 11),
('Alta Floresta', 11),
('Alto Araguaia', 11),
('Alto Boa Vista', 11),
('Alto Garcas', 11),
('Alto Paraguai', 11),
('Alto Taquari', 11),
('Apiacas', 11),
('Araguaiana', 11),
('Araguainha', 11),
('Araputanga', 11),
('Arenapolis', 11),
('Aripuana', 11),
('Barao de Melgaco', 11),
('Barra do Bugres', 11),
('Barra do Garcas', 11),
('Brasnorte', 11),
('Caceres', 11),
('Campinapolis', 11),
('Campo Novo do Parecis', 11),
('Campo Verde', 11),
('Campos de Julio', 11),
('Cana Brava do Norte', 11),
('Canarana', 11),
('Carlinda', 11),
('Castanheira', 11),
('Chapada dos Guimaraes', 11),
('Claudia', 11),
('Cocalinho', 11),
('Colider', 11),
('Comodoro', 11),
('Confresa', 11),
('Cotriguacu', 11),
('Cuiaba', 11),
('Denise', 11),
('Diamantino', 11),
('Dom Aquino', 11),
('Feliz Natal', 11),
('Figueiropolis d\'Oeste', 11),
('Gaucha do Norte', 11),
('General Carneiro', 11),
('Gloria d\'Oeste', 11),
('Guaranta do Norte', 11),
('Guiratinga', 11),
('Indiavai', 11),
('Itauba', 11),
('Itiquira', 11),
('Jaciara', 11),
('Jangada', 11),
('Jauru', 11),
('Juara', 11),
('Juina', 11),
('Juruena', 11),
('Juscimeira', 11),
('Lambari d\'Oeste', 11),
('Lucas do Rio Verde', 11),
('Luciara', 11),
('Marcelandia', 11),
('Matupa', 11),
('Mirassol d\'Oeste', 11),
('Nobres', 11),
('Nortelandia', 11),
('Nossa Senhora do Livramento', 11),
('Nova Bandeirantes', 11),
('Nova Brasilandia', 11),
('Nova Canaa do Norte', 11),
('Nova Guarita', 11),
('Nova Lacerda', 11),
('Nova Marilandia', 11),
('Nova Maringa', 11),
('Nova Monte Verde', 11),
('Nova Mutum', 11),
('Nova Olimpia', 11),
('Nova Ubirata', 11),
('Nova Xavantina', 11),
('Novo Horizonte do Norte', 11),
('Novo Mundo', 11),
('Novo Sao Joaquim', 11),
('Paranaita', 11),
('Paranatinga', 11),
('Pedra Preta', 11),
('Peixoto de Azevedo', 11),
('Planalto da Serra', 11),
('Pocone', 11),
('Pontal do Araguaia', 11),
('Ponte Branca', 11),
('Pontes e Lacerda', 11),
('Porto Alegre do Norte', 11),
('Porto Esperidiao', 11),
('Porto Estrela', 11),
('Porto dos Gauchos', 11),
('Poxoreo', 11),
('Primavera do Leste', 11),
('Querencia', 11),
('Reserva do Cabacal', 11),
('Ribeirao Cascalheira', 11),
('Ribeiraozinho', 11),
('Rio Branco', 11),
('Rondonopolis', 11),
('Rosario Oeste', 11),
('Salto do Ceu', 11),
('Santa Carmem', 11),
('Santa Terezinha', 11),
('Santo Afonso', 11),
('Santo Antonio do Leverger', 11),
('Sao Felix do Araguaia', 11),
('Sao Jose do Povo', 11),
('Sao Jose do Rio Claro', 11),
('Sao Jose do Xingu', 11),
('Sao Jose dos Quatro Marcos', 11),
('Sao Pedro da Cipa', 11),
('Sapezal', 11),
('Sinop', 11),
('Sorriso', 11),
('Tabapora', 11),
('Tangara da Serra', 11),
('Tapurah', 11),
('Terra Nova do Norte', 11),
('Tesouro', 11),
('Torixoreu', 11),
('Uniao do Sul', 11),
('Varzea Grande', 11),
('Vera', 11),
('Vila Bela da Santissima Trindade', 11),
('Vila Rica', 11);