INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

 	
('Alvaraes', 4),
('Amatura', 4),
('Anama', 4),
('Anori', 4),
('Apui', 4),
('Atalaia do Norte', 4),
('Autazes', 4),
('Barcelos', 4),
('Barreirinha', 4),
('Benjamin Constant', 4),
('Beruri', 4),
('Boa Vista do Ramos', 4),
('Boca do Acre', 4),
('Borba', 4),
('Caapiranga', 4),
('Canutama', 4),
('Carauari', 4),
('Careiro da Varzea', 4),
('Careiro', 4),
('Coari', 4),
('Codajas', 4),
('Eirunepe', 4),
('Envira', 4),
('Fonte Boa', 4),
('Guajara', 4),
('Humaita', 4),
('Ipixuna', 4),
('Iranduba', 4),
('Itacoatiara', 4),
('Itamarati', 4),
('Itapiranga', 4),
('Japura', 4),
('Jurua', 4),
('Jutai', 4),
('Labrea', 4),
('Manacapuru', 4),
('Manaquiri', 4),
('Manaus', 4),
('Manicore', 4),
('Maraa', 4),
('Maues', 4),
('Nhamunda', 4),
('Nova Olinda do Norte', 4),
('Novo Airao', 4),
('Novo Aripuana', 4),
('Parintins', 4),
('Pauini', 4),
('Presidente Figueiredo', 4),
('Rio Preto da Eva', 4),
('Santa Isabel do Rio Negro', 4),
('Santo Antonio do Ica', 4),
('Sao Gabriel da Cachoeira', 4),
('Sao Paulo de Olivenca', 4),
('Sao Sebastiao do Uatuma', 4),
('Silves', 4),
('Tabatinga', 4),
('Tapaua', 4),
('Tefe', 4),
('Tonantins', 4),
('Uarini', 4),
('Urucara', 4),
('Urucurituba', 4);