INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Afonso Claudio', 8),
('Agua Doce do Norte', 8),
('Aguia Branca', 8),
('Alegre', 8),
('Alfredo Chaves', 8),
('Alto Rio Novo', 8),
('Anchieta', 8),
('Apiaca', 8),
('Aracruz', 8),
('Atilio Vivacqua', 8),
('Baixo Guandu', 8),
('Barra de Sao Francisco', 8),
('Boa Esperanca', 8),
('Bom Jesus do Norte', 8),
('Brejetuba', 8),
('Cachoeiro de Itapemirim', 8),
('Cariacica', 8),
('Castelo', 8),
('Colatina', 8),
('Conceicao da Barra', 8),
('Conceicao do Castelo', 8),
('Divino de Sao Lourenco', 8),
('Domingos Martins', 8),
('Dores do Rio Preto', 8),
('Ecoporanga', 8),
('Fundao', 8),
('Guacui', 8),
('Guarapari', 8),
('Ibatiba', 8),
('Ibiracu', 8),
('Ibitirama', 8),
('Iconha', 8),
('Irupi', 8),
('Itaguacu', 8),
('Itapemirim', 8),
('Itarana', 8),
('Iuna', 8),
('Jaguare', 8),
('Jeronimo Monteiro', 8),
('Joao Neiva', 8),
('Laranja da Terra', 8),
('Linhares', 8),
('Mantenopolis', 8),
('Marataizes', 8),
('Marechal Floriano', 8),
('Marilandia', 8),
('Mimoso do Sul', 8),
('Montanha', 8),
('Mucurici', 8),
('Muniz Freire', 8),
('Muqui', 8),
('Nova Venecia', 8),
('Pancas', 8),
('Pedro Canario', 8),
('Pinheiros', 8),
('Piuma', 8),
('Ponto Belo', 8),
('Presidente Kennedy', 8),
('Rio Bananal', 8),
('Rio Novo do Sul', 8),
('Santa Leopoldina', 8),
('Santa Maria de Jetiba', 8),
('Santa Teresa', 8),
('Sao Domingos do Norte', 8),
('Sao Gabriel da Palha', 8),
('Sao Jose do Calcado', 8),
('Sao Mateus', 8),
('Sao Roque do Canaa', 8),
('Serra', 8),
('Sooretama', 8),
('Vargem Alta', 8),
('Venda Nova do Imigrante', 8),
('Viana', 8),
('Vila Pavao', 8),
('Vila Valerio', 8),
('Vila Velha', 8),
('Vitoria', 8);