INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abaira', 5),
('Abare', 5),
('Acajutiba', 5),
('Adustina', 5),
('Agua Fria', 5),
('Aiquara', 5),
('Alagoinhas', 5),
('Alcobaca', 5),
('Almadina', 5),
('Amargosa', 5),
('Amelia Rodrigues', 5),
('America Dourada', 5),
('Anage', 5),
('Andarai', 5),
('Andorinha', 5),
('Angical', 5),
('Anguera', 5),
('Antas', 5),
('Antonio Cardoso', 5),
('Antonio Goncalves', 5),
('Apora', 5),
('Apuarema', 5),
('Aracas', 5),
('Aracatu', 5),
('Araci', 5),
('Aramari', 5),
('Arataca', 5),
('Aratuipe', 5),
('Aurelino Leal', 5),
('Baianopolis', 5),
('Baixa Grande', 5),
('Banzae', 5),
('Barra da Estiva', 5),
('Barra do Choca', 5),
('Barra do Mendes', 5),
('Barra do Rocha', 5),
('Barra', 5),
('Barreiras', 5),
('Barro Alto', 5),
('Barro Preto', 5),
('Belmonte', 5),
('Belo Campo', 5),
('Biritinga', 5),
('Boa Nova', 5),
('Boa Vista do Tupim', 5),
('Bom Jesus da Lapa', 5),
('Bom Jesus da Serra', 5),
('Boninal', 5),
('Bonito', 5),
('Boquira', 5),
('Botupora', 5),
('Brejoes', 5),
('Brejolandia', 5),
('Brotas de Macaubas', 5),
('Brumado', 5),
('Buerarema', 5),
('Buritirama', 5),
('Caatiba', 5),
('Cabaceiras do Paraguacu', 5),
('Cachoeira', 5),
('Cacule', 5),
('Caem', 5),
('Caetanos', 5),
('Caetite', 5),
('Cafarnaum', 5),
('Cairu', 5),
('Caldeirao Grande', 5),
('Camacan', 5),
('Camacari', 5),
('Camamu', 5),
('Campo Alegre de Lourdes', 5),
('Campo Formoso', 5),
('Canapolis', 5),
('Canarana', 5),
('Canavieiras', 5),
('Candeal', 5),
('Candeias', 5),
('Candiba', 5),
('Candido Sales', 5),
('Cansancao', 5),
('Canudos', 5),
('Capela do Alto Alegre', 5),
('Capim Grosso', 5),
('Caraibas', 5),
('Caravelas', 5),
('Cardeal da Silva', 5),
('Carinhanha', 5),
('Casa Nova', 5),
('Castro Alves', 5),
('Catolandia', 5),
('Catu', 5),
('Caturama', 5),
('Central', 5),
('Chorrocho', 5),
('Cicero Dantas', 5),
('Cipo', 5),
('Coaraci', 5),
('Cocos', 5),
('Conceicao da Feira', 5),
('Conceicao do Almeida', 5),
('Conceicao do Coite', 5),
('Conceicao do Jacuipe', 5),
('Conde', 5),
('Condeuba', 5),
('Contendas do Sincora', 5),
('Coracao de Maria', 5),
('Cordeiros', 5),
('Coribe', 5),
('Coronel Joao Sa', 5),
('Correntina', 5),
('Cotegipe', 5),
('Cravolandia', 5),
('Crisopolis', 5),
('Cristopolis', 5),
('Cruz das Almas', 5),
('Curaca', 5),
('Dario Meira', 5),
('Dias d\'Avila', 5),
('Dom Basilio', 5),
('Dom Macedo Costa', 5),
('Elisio Medrado', 5),
('Encruzilhada', 5),
('Entre Rios', 5),
('Erico Cardoso', 5),
('Esplanada', 5),
('Euclides da Cunha', 5),
('Eunapolis', 5),
('Fatima', 5),
('Feira da Mata', 5),
('Feira de Santana', 5),
('Filadelfia', 5),
('Firmino Alves', 5),
('Floresta Azul', 5),
('Formosa do Rio Preto', 5),
('Gandu', 5),
('Gaviao', 5),
('Gentio do Ouro', 5),
('Gloria', 5),
('Gongogi', 5),
('Governador Mangabeira', 5),
('Guajeru', 5),
('Guanambi', 5),
('Guaratinga', 5),
('Heliopolis', 5),
('Iacu', 5),
('Ibiassuce', 5),
('Ibicarai', 5),
('Ibicoara', 5),
('Ibicui', 5),
('Ibipeba', 5),
('Ibipitanga', 5),
('Ibiquera', 5),
('Ibirapitanga', 5),
('Ibirapua', 5),
('Ibirataia', 5),
('Ibitiara', 5),
('Ibitita', 5),
('Ibotirama', 5),
('Ichu', 5),
('Igapora', 5),
('Igrapiuna', 5),
('Iguai', 5),
('Ilheus', 5),
('Inhambupe', 5),
('Ipecaeta', 5),
('Ipiau', 5),
('Ipira', 5),
('Ipupiara', 5),
('Irajuba', 5),
('Iramaia', 5),
('Iraquara', 5),
('Irara', 5),
('Irece', 5),
('Itabela', 5),
('Itaberaba', 5),
('Itabuna', 5),
('Itacare', 5),
('Itaete', 5),
('Itagi', 5),
('Itagiba', 5),
('Itagimirim', 5),
('Itaguacu da Bahia', 5),
('Itaju do Colonia', 5),
('Itajuipe', 5),
('Itamaraju', 5),
('Itamari', 5),
('Itambe', 5),
('Itanagra', 5),
('Itanhem', 5),
('Itaparica', 5),
('Itape', 5),
('Itapebi', 5),
('Itapetinga', 5),
('Itapicuru', 5),
('Itapitanga', 5),
('Itaquara', 5),
('Itarantim', 5),
('Itatim', 5),
('Itirucu', 5),
('Itiuba', 5),
('Itororo', 5),
('Ituacu', 5),
('Itubera', 5),
('Iuiu', 5),
('Jaborandi', 5),
('Jacaraci', 5),
('Jacobina', 5),
('Jaguaquara', 5),
('Jaguarari', 5),
('Jaguaripe', 5),
('Jandaira', 5),
('Jequie', 5),
('Jeremoabo', 5),
('Jiquirica', 5),
('Jitauna', 5),
('Joao Dourado', 5),
('Juazeiro', 5),
('Jucurucu', 5),
('Jussara', 5),
('Jussari', 5),
('Jussiape', 5),
('Lafaiete Coutinho', 5),
('Lagoa Real', 5),
('Laje', 5),
('Lajedao', 5),
('Lajedinho', 5),
('Lajedo do Tabocal', 5),
('Lamarao', 5),
('Lapao', 5),
('Lauro de Freitas', 5),
('Lencois', 5),
('Licinio de Almeida', 5),
('Livramento do Brumado', 5),
('Macajuba', 5),
('Macarani', 5),
('Macaubas', 5),
('Macurure', 5),
('Madre de Deus', 5),
('Maetinga', 5),
('Maiquinique', 5),
('Mairi', 5),
('Malhada de Pedras', 5),
('Malhada', 5),
('Manoel Vitorino', 5),
('Mansidao', 5),
('Maracas', 5),
('Maragogipe', 5),
('Marau', 5),
('Marcionilio Souza', 5),
('Mascote', 5),
('Mata de Sao Joao', 5),
('Matina', 5),
('Medeiros Neto', 5),
('Miguel Calmon', 5),
('Milagres', 5),
('Mirangaba', 5),
('Mirante', 5),
('Monte Santo', 5),
('Morpara', 5),
('Morro do Chapeu', 5),
('Mortugaba', 5),
('Mucuge', 5),
('Mucuri', 5),
('Mulungu do Morro', 5),
('Mundo Novo', 5),
('Muniz Ferreira', 5),
('Muquem de Sao Francisco', 5),
('Muritiba', 5),
('Mutuipe', 5),
('Nazare', 5),
('Nilo Pecanha', 5),
('Nordestina', 5),
('Nova Canaa', 5),
('Nova Fatima', 5),
('Nova Ibia', 5),
('Nova Itarana', 5),
('Nova Redencao', 5),
('Nova Soure', 5),
('Nova Vicosa', 5),
('Novo Horizonte', 5),
('Novo Triunfo', 5),
('Olindina', 5),
('Oliveira dos Brejinhos', 5),
('Ouricangas', 5),
('Ourolandia', 5),
('Palmas de Monte Alto', 5),
('Palmeiras', 5),
('Paramirim', 5),
('Paratinga', 5),
('Paripiranga', 5),
('Pau Brasil', 5),
('Paulo Afonso', 5),
('Pe de Serra', 5),
('Pedrao', 5),
('Pedro Alexandre', 5),
('Piata', 5),
('Pilao Arcado', 5),
('Pindai', 5),
('Pindobacu', 5),
('Pintadas', 5),
('Pirai do Norte', 5),
('Piripa', 5),
('Piritiba', 5),
('Planaltino', 5),
('Planalto', 5),
('Pocoes', 5),
('Pojuca', 5),
('Ponto Novo', 5),
('Porto Seguro', 5),
('Potiragua', 5),
('Prado', 5),
('Presidente Dutra', 5),
('Presidente Janio Quadros', 5),
('Presidente Tancredo Neves', 5),
('Queimadas', 5),
('Quijingue', 5),
('Quixabeira', 5),
('Rafael Jambeiro', 5),
('Remanso', 5),
('Retirolandia', 5),
('Riachao das Neves', 5),
('Riachao do Jacuipe', 5),
('Riacho de Santana', 5),
('Ribeira do Amparo', 5),
('Ribeira do Pombal', 5),
('Ribeirao do Largo', 5),
('Rio Real', 5),
('Rio de Contas', 5),
('Rio do Antonio', 5),
('Rio do Pires', 5),
('Rodelas', 5),
('Ruy Barbosa', 5),
('Salinas da Margarida', 5),
('Salvador', 5),
('Santa Barbara', 5),
('Santa Brigida', 5),
('Santa Cruz Cabralia', 5),
('Santa Cruz da Vitoria', 5),
('Santa Ines', 5),
('Santa Luzia', 5),
('Santa Maria da Vitoria', 5),
('Santa Rita de Cassia', 5),
('Santa Teresinha', 5),
('Santaluz', 5),
('Santana', 5),
('Santanopolis', 5),
('Santo Amaro', 5),
('Santo Antonio de Jesus', 5),
('Santo Estevao', 5),
('Sao Desiderio', 5),
('Sao Domingos', 5),
('Sao Felipe', 5),
('Sao Felix do Coribe', 5),
('Sao Felix', 5),
('Sao Francisco do Conde', 5),
('Sao Gabriel', 5),
('Sao Goncalo dos Campos', 5),
('Sao Jose da Vitoria', 5),
('Sao Jose do Jacuipe', 5),
('Sao Miguel das Matas', 5),
('Sao Sebastiao do Passe', 5),
('Sapeacu', 5),
('Satiro Dias', 5),
('Saubara', 5),
('Saude', 5),
('Seabra', 5),
('Sebastiao Laranjeiras', 5),
('Senhor do Bonfim', 5),
('Sento Se', 5),
('Serra Dourada', 5),
('Serra Preta', 5),
('Serra do Ramalho', 5),
('Serrinha', 5),
('Serrolandia', 5),
('Simoes Filho', 5),
('Sitio do Mato', 5),
('Sitio do Quinto', 5),
('Sobradinho', 5),
('Souto Soares', 5),
('Tabocas do Brejo Velho', 5),
('Tanhacu', 5),
('Tanque Novo', 5),
('Tanquinho', 5),
('Taperoa', 5),
('Tapiramuta', 5),
('Teixeira de Freitas', 5),
('Teodoro Sampaio', 5),
('Teofilandia', 5),
('Teolandia', 5),
('Terra Nova', 5),
('Tremedal', 5),
('Tucano', 5),
('Uaua', 5),
('Ubaira', 5),
('Ubaitaba', 5),
('Ubata', 5),
('Uibai', 5),
('Umburanas', 5),
('Una', 5),
('Urandi', 5),
('Urucuca', 5),
('Utinga', 5),
('Valenca', 5),
('Valente', 5),
('Varzea Nova', 5),
('Varzea da Roca', 5),
('Varzea do Poco', 5),
('Varzedo', 5),
('Vera Cruz', 5),
('Vereda', 5),
('Vitoria da Conquista', 5),
('Wagner', 5),
('Wanderley', 5),
('Wenceslau Guimaraes', 5),
('Xique-Xique', 5);