INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Agua Santa', 21),
('Agudo', 21),
('Ajuricaba', 21),
('Alecrim', 21),
('Alegrete', 21),
('Alegria', 21),
('Alpestre', 21),
('Alto Alegre', 21),
('Alto Feliz', 21),
('Alvorada', 21),
('Amaral Ferrador', 21),
('Ametista do Sul', 21),
('Andre da Rocha', 21),
('Anta Gorda', 21),
('Antonio Prado', 21),
('Arambare', 21),
('Ararica', 21),
('Aratiba', 21),
('Arroio Grande', 21),
('Arroio do Meio', 21),
('Arroio do Sal', 21),
('Arroio do Tigre', 21),
('Arroio dos Ratos', 21),
('Arvorezinha', 21),
('Augusto Pestana', 21),
('Aurea', 21),
('Bage', 21),
('Balneario Pinhal', 21),
('Barao de Cotegipe', 21),
('Barao do Triunfo', 21),
('Barao', 21),
('Barra Funda', 21),
('Barra do Guarita', 21),
('Barra do Quarai', 21),
('Barra do Ribeiro', 21),
('Barra do Rio Azul', 21),
('Barracao', 21),
('Barros Cassal', 21),
('Benjamin Constant do Sul', 21),
('Bento Goncalves', 21),
('Boa Vista das Missoes', 21),
('Boa Vista do Burica', 21),
('Boa Vista do Sul', 21),
('Bom Jesus', 21),
('Bom Principio', 21),
('Bom Progresso', 21),
('Bom Retiro do Sul', 21),
('Boqueirao do Leao', 21),
('Bossoroca', 21),
('Braga', 21),
('Brochier', 21),
('Butia', 21),
('Cacapava do Sul', 21),
('Cacequi', 21),
('Cachoeira do Sul', 21),
('Cachoeirinha', 21),
('Cacique Doble', 21),
('Caibate', 21),
('Caicara', 21),
('Camaqua', 21),
('Camargo', 21),
('Cambara do Sul', 21),
('Campestre da Serra', 21),
('Campina das Missoes', 21),
('Campinas do Sul', 21),
('Campo Bom', 21),
('Campo Novo', 21),
('Campos Borges', 21),
('Candelaria', 21),
('Candido Godoi', 21),
('Candiota', 21),
('Canela', 21),
('Cangucu', 21),
('Canoas', 21),
('Capao da Canoa', 21),
('Capao do Leao', 21),
('Capela de Santana', 21),
('Capitao', 21),
('Capivari do Sul', 21),
('Caraa', 21),
('Carazinho', 21),
('Carlos Barbosa', 21),
('Carlos Gomes', 21),
('Casca', 21),
('Caseiros', 21),
('Catuipe', 21),
('Caxias do Sul', 21),
('Centenario', 21),
('Cerrito', 21),
('Cerro Branco', 21),
('Cerro Grande do Sul', 21),
('Cerro Grande', 21),
('Cerro Largo', 21),
('Chapada', 21),
('Charqueadas', 21),
('Charrua', 21),
('Chiapeta', 21),
('Chui', 21),
('Chuvisca', 21),
('Cidreira', 21),
('Ciriaco', 21),
('Colinas', 21),
('Colorado', 21),
('Condor', 21),
('Constantina', 21),
('Coqueiros do Sul', 21),
('Coronel Barros', 21),
('Coronel Bicaco', 21),
('Cotipora', 21),
('Coxilha', 21),
('Crissiumal', 21),
('Cristal do Sul', 21),
('Cristal', 21),
('Cruz Alta', 21),
('Cruzeiro do Sul', 21),
('David Canabarro', 21),
('Derrubadas', 21),
('Dezesseis de Novembro', 21),
('Dilermano de Aguiar', 21),
('Dois Irmaos das Missoes', 21),
('Dois Irmaos', 21),
('Dois Lajeados', 21),
('Dom Feliciano', 21),
('Dom Pedrito', 21),
('Dom Pedro de Alcantara', 21),
('Dona Francisca', 21),
('Doutor Mauricio Cardoso', 21),
('Doutor Ricardo', 21),
('Eldorado do Sul', 21),
('Encantado', 21),
('Encruzilhada do Sul', 21),
('Engenho Velho', 21),
('Entre Rios do Sul', 21),
('Entre-Ijuis', 21),
('Erebango', 21),
('Erechim', 21),
('Ernestina', 21),
('Erval Grande', 21),
('Erval Seco', 21),
('Esmeralda', 21),
('Esperanca do Sul', 21),
('Espumoso', 21),
('Estacao', 21),
('Estancia Velha', 21),
('Esteio', 21),
('Estrela Velha', 21),
('Estrela', 21),
('Eugenio de Castro', 21),
('Fagundes Varela', 21),
('Farroupilha', 21),
('Faxinal do Soturno', 21),
('Faxinalzinho', 21),
('Fazenda Vilanova', 21),
('Feliz', 21),
('Flores da Cunha', 21),
('Floriano Peixoto', 21),
('Fontoura Xavier', 21),
('Formigueiro', 21),
('Fortaleza dos Valos', 21),
('Frederico Westphalen', 21),
('Garibaldi', 21),
('Garruchos', 21),
('Gaurama', 21),
('General Camara', 21),
('Gentil', 21),
('Getulio Vargas', 21),
('Girua', 21),
('Glorinha', 21),
('Gramado Xavier', 21),
('Gramado dos Loureiros', 21),
('Gramado', 21),
('Gravatai', 21),
('Guabiju', 21),
('Guaiba', 21),
('Guapore', 21),
('Guarani das Missoes', 21),
('Harmonia', 21),
('Herval', 21),
('Herveiras', 21),
('Horizontina', 21),
('Hulha Negra', 21),
('Humaita', 21),
('Ibarama', 21),
('Ibiaca', 21),
('Ibiraiaras', 21),
('Ibirapuita', 21),
('Ibiruba', 21),
('Igrejinha', 21),
('Ijui', 21),
('Ilopolis', 21),
('Imbe', 21),
('Imigrante', 21),
('Independencia', 21),
('Inhacora', 21),
('Ipe', 21),
('Ipiranga do Sul', 21),
('Irai', 21),
('Itaara', 21),
('Itacurubi', 21),
('Itapuca', 21),
('Itaqui', 21),
('Itatiba do Sul', 21),
('Ivora', 21),
('Ivoti', 21),
('Jaboticaba', 21),
('Jacutinga', 21),
('Jaguarao', 21),
('Jaguari', 21),
('Jaquirana', 21),
('Jari', 21),
('Joia', 21),
('Julio de Castilhos', 21),
('Lagoa Vermelha', 21),
('Lagoa dos Tres Cantos', 21),
('Lagoao', 21),
('Lajeado do Bugre', 21),
('Lajeado', 21),
('Lavras do Sul', 21),
('Liberato Salzano', 21),
('Lindolfo Collor', 21),
('Linha Nova', 21),
('Macambara', 21),
('Machadinho', 21),
('Mampituba', 21),
('Manoel Viana', 21),
('Maquine', 21),
('Marata', 21),
('Marau', 21),
('Marcelino Ramos', 21),
('Mariana Pimentel', 21),
('Mariano Moro', 21),
('Marques de Souza', 21),
('Mata', 21),
('Mato Castelhano', 21),
('Mato Leitao', 21),
('Maximiliano de Almeida', 21),
('Minas do Leao', 21),
('Miraguai', 21),
('Montauri', 21),
('Monte Alegre dos Campos', 21),
('Monte Belo do Sul', 21),
('Montenegro', 21),
('Mormaco', 21),
('Morrinhos do Sul', 21),
('Morro Redondo', 21),
('Morro Reuter', 21),
('Mostardas', 21),
('Mucum', 21),
('Muitos Capoes', 21),
('Muliterno', 21),
('Nao-Me-Toque', 21),
('Nicolau Vergueiro', 21),
('Nonoai', 21),
('Nova Alvorada', 21),
('Nova Araca', 21),
('Nova Bassano', 21),
('Nova Boa Vista', 21),
('Nova Brescia', 21),
('Nova Candelaria', 21),
('Nova Esperanca do Sul', 21),
('Nova Hartz', 21),
('Nova Padua', 21),
('Nova Palma', 21),
('Nova Petropolis', 21),
('Nova Prata', 21),
('Nova Ramada', 21),
('Nova Roma do Sul', 21),
('Nova Santa Rita', 21),
('Novo Barreiro', 21),
('Novo Cabrais', 21),
('Novo Hamburgo', 21),
('Novo Machado', 21),
('Novo Tiradentes', 21),
('Osorio', 21),
('Paim Filho', 21),
('Palmares do Sul', 21),
('Palmeira das Missoes', 21),
('Palmitinho', 21),
('Panambi', 21),
('Pantano Grande', 21),
('Parai', 21),
('Paraiso do Sul', 21),
('Pareci Novo', 21),
('Parobe', 21),
('Passa Sete', 21),
('Passo Fundo', 21),
('Passo do Sobrado', 21),
('Paverama', 21),
('Pedro Osorio', 21),
('Pejucara', 21),
('Pelotas', 21),
('Picada Cafe', 21),
('Pinhal Grande', 21),
('Pinhal', 21),
('Pinheirinho do Vale', 21),
('Pinheiro Machado', 21),
('Pirapo', 21),
('Piratini', 21),
('Planalto', 21),
('Poco das Antas', 21),
('Pontao', 21),
('Ponte Preta', 21),
('Portao', 21),
('Porto Alegre', 21),
('Porto Lucena', 21),
('Porto Maua', 21),
('Porto Vera Cruz', 21),
('Porto Xavier', 21),
('Pouso Novo', 21),
('Presidente Lucena', 21),
('Progresso', 21),
('Protasio Alves', 21),
('Putinga', 21),
('Quarai', 21),
('Quevedos', 21),
('Quinze de Novembro', 21),
('Redentora', 21),
('Relvado', 21),
('Restinga Seca', 21),
('Rio Grande', 21),
('Rio Pardo', 21),
('Rio dos Indios', 21),
('Riozinho', 21),
('Roca Sales', 21),
('Rodeio Bonito', 21),
('Rolante', 21),
('Ronda Alta', 21),
('Rondinha', 21),
('Roque Gonzales', 21),
('Rosario do Sul', 21),
('Sagrada Familia', 21),
('Saldanha Marinho', 21),
('Salto do Jacui', 21),
('Salvador das Missoes', 21),
('Salvador do Sul', 21),
('Sananduva', 21),
('Santa Barbara do Sul', 21),
('Santa Clara do Sul', 21),
('Santa Cruz do Sul', 21),
('Santa Maria do Herval', 21),
('Santa Maria', 21),
('Santa Rosa', 21),
('Santa Tereza', 21),
('Santa Vitoria do Palmar', 21),
('Santana da Boa Vista', 21),
('Santana do Livramento', 21),
('Santiago', 21),
('Santo Angelo', 21),
('Santo Antonio da Patrulha', 21),
('Santo Antonio das Missoes', 21),
('Santo Antonio do Palma', 21),
('Santo Antonio do Planalto', 21),
('Santo Augusto', 21),
('Santo Cristo', 21),
('Santo Expedito do Sul', 21),
('Sao Borja', 21),
('Sao Domingos do Sul', 21),
('Sao Francisco de Assis', 21),
('Sao Francisco de Paula', 21),
('Sao Gabriel', 21),
('Sao Jeronimo', 21),
('Sao Joao da Urtiga', 21),
('Sao Joao do Polesine', 21),
('Sao Jorge', 21),
('Sao Jose das Missoes', 21),
('Sao Jose do Herval', 21),
('Sao Jose do Hortencio', 21),
('Sao Jose do Inhacora', 21),
('Sao Jose do Norte', 21),
('Sao Jose do Ouro', 21),
('Sao Jose dos Ausentes', 21),
('Sao Leopoldo', 21),
('Sao Lourenco do Sul', 21),
('Sao Luiz Gonzaga', 21),
('Sao Marcos', 21),
('Sao Martinho da Serra', 21),
('Sao Martinho', 21),
('Sao Miguel das Missoes', 21),
('Sao Nicolau', 21),
('Sao Paulo das Missoes', 21),
('Sao Pedro da Serra', 21),
('Sao Pedro do Butia', 21),
('Sao Pedro do Sul', 21),
('Sao Sebastiao do Cai', 21),
('Sao Sepe', 21),
('Sao Valentim do Sul', 21),
('Sao Valentim', 21),
('Sao Valerio do Sul', 21),
('Sao Vendelino', 21),
('Sao Vicente do Sul', 21),
('Sapiranga', 21),
('Sapucaia do Sul', 21),
('Sarandi', 21),
('Seberi', 21),
('Sede Nova', 21),
('Segredo', 21),
('Selbach', 21),
('Senador Salgado Filho', 21),
('Sentinela do Sul', 21),
('Serafina Correa', 21),
('Serio', 21),
('Sertao Santana', 21),
('Sertao', 21),
('Sete de Setembro', 21),
('Severiano de Almeida', 21),
('Silveira Martins', 21),
('Sinimbu', 21),
('Sobradinho', 21),
('Soledade', 21),
('Tabai', 21),
('Tapejara', 21),
('Tapera', 21),
('Tapes', 21),
('Taquara', 21),
('Taquari', 21),
('Taquarucu do Sul', 21),
('Tavares', 21),
('Tenente Portela', 21),
('Terra de Areia', 21),
('Teutonia', 21),
('Tiradentes do Sul', 21),
('Toropi', 21),
('Torres', 21),
('Tramandai', 21),
('Travesseiro', 21),
('Tres Arroios', 21),
('Tres Cachoeiras', 21),
('Tres Coroas', 21),
('Tres Forquilhas', 21),
('Tres Palmeiras', 21),
('Tres Passos', 21),
('Tres de Maio', 21),
('Trindade do Sul', 21),
('Triunfo', 21),
('Tucunduva', 21),
('Tunas', 21),
('Tupanci do Sul', 21),
('Tupancireta', 21),
('Tupandi', 21),
('Tuparendi', 21),
('Turucu', 21),
('Ubiretama', 21),
('Uniao da Serra', 21),
('Unistalda', 21),
('Uruguaiana', 21),
('Vacaria', 21),
('Vale Real', 21),
('Vale Verde', 21),
('Vale do Sol', 21),
('Vanini', 21),
('Venancio Aires', 21),
('Vera Cruz', 21),
('Veranopolis', 21),
('Vespasiano Correa', 21),
('Viadutos', 21),
('Viamao', 21),
('Vicente Dutra', 21),
('Victor Graeff', 21),
('Vila Flores', 21),
('Vila Langaro', 21),
('Vila Maria', 21),
('Vila Nova do Sul', 21),
('Vista Alegre do Prata', 21),
('Vista Alegre', 21),
('Vista Gaucha', 21),
('Vitoria das Missoes', 21),
('Xangri-la', 21);