INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Agua Branca', 2),
('Anadia', 2),
('Arapiraca', 2),
('Atalaia', 2),
('Barra de Santo Antonio', 2),
('Barra de Sao Miguel', 2),
('Batalha', 2),
('Belem', 2),
('Belo Monte', 2),
('Boca da Mata', 2),
('Branquinha', 2),
('Cacimbinhas', 2),
('Cajueiro', 2),
('Campestre', 2),
('Campo Alegre', 2),
('Campo Grande', 2),
('Canapi', 2),
('Capela', 2),
('Carneiros', 2),
('Cha Preta', 2),
('Coite do Noia', 2),
('Colonia Leopoldina', 2),
('Coqueiro Seco', 2),
('Coruripe', 2),
('Craibas', 2),
('Delmiro Gouveia', 2),
('Dois Riachos', 2),
('Estrela de Alagoas', 2),
('Feira Grande', 2),
('Feliz Deserto', 2),
('Flexeiras', 2),
('Girau do Ponciano', 2),
('Ibateguara', 2),
('Igaci', 2),
('Igreja Nova', 2),
('Inhapi', 2),
('Jacare dos Homens', 2),
('Jacuipe', 2),
('Japaratinga', 2),
('Jaramataia', 2),
('Joaquim Gomes', 2),
('Jequia da Praia ', 2),
('Jundia', 2),
('Junqueiro', 2),
('Lagoa da Canoa', 2),
('Limoeiro de Anadia', 2),
('Maceio', 2),
('Major Isidoro', 2),
('Mar Vermelho', 2),
('Maragogi', 2),
('Maravilha', 2),
('Marechal Deodoro', 2),
('Maribondo', 2),
('Mata Grande', 2),
('Matriz de Camaragibe', 2),
('Messias', 2),
('Minador do Negrao', 2),
('Monteiropolis', 2),
('Murici', 2),
('Novo Lino', 2),
('Olho d\'Agua Grande', 2),
('Olho d\'Agua das Flores', 2),
('Olho d\'Agua do Casado', 2),
('Olivenca', 2),
('Ouro Branco', 2),
('Palestina', 2),
('Palmeira dos Indios', 2),
('Pao de Acucar', 2),
('Pariconha', 2),
('Paripueira', 2),
('Passo de Camaragibe', 2),
('Paulo Jacinto', 2),
('Penedo', 2),
('Piacabucu', 2),
('Pilar', 2),
('Pindoba', 2),
('Piranhas', 2),
('Poco das Trincheiras', 2),
('Porto Calvo', 2),
('Porto Real do Colegio', 2),
('Porto de Pedras', 2),
('Quebrangulo', 2),
('Rio Largo', 2),
('Roteiro', 2),
('Santa Luzia do Norte', 2),
('Santana do Ipanema', 2),
('Santana do Mundau', 2),
('Sao Bras', 2),
('Sao Jose da Laje', 2),
('Sao Jose da Tapera', 2),
('Sao Luis do Quitunde', 2),
('Sao Miguel dos Campos', 2),
('Sao Miguel dos Milagres', 2),
('Sao Sebastiao', 2),
('Satuba', 2),
('Senador Rui Palmeira', 2),
('Tanque d\'Arca', 2),
('Taquarana', 2),
('Teotonio Vilela', 2),
('Traipu', 2),
('Uniao dos Palmares', 2),
('Vicosa', 2);