INSERT INTO `mundo`.`cidade`
(`nomeCidade`,
`estado_idEstado`)
VALUES

('Abadia de Goias', 9),
('Abadiania', 9),
('Acreuna', 9),
('Adelandia', 9),
('Agua Fria de Goias', 9),
('Agua Limpa', 9),
('Aguas Lindas de Goias', 9),
('Alexania', 9),
('Aloandia', 9),
('Alto Horizonte', 9),
('Alto Paraiso de Goias', 9),
('Alvorada do Norte', 9),
('Amaralina', 9),
('Americano do Brasil', 9),
('Amorinopolis', 9),
('Anapolis', 9),
('Anhanguera', 9),
('Anicuns', 9),
('Aparecida de Goiania', 9),
('Aparecida do Rio Doce', 9),
('Apore', 9),
('Aracu', 9),
('Aragarcas', 9),
('Aragoiania', 9),
('Araguapaz', 9),
('Arenopolis', 9),
('Aruana', 9),
('Aurilandia', 9),
('Avelinopolis', 9),
('Baliza', 9),
('Barro Alto', 9),
('Bela Vista de Goias', 9),
('Bom Jardim de Goias', 9),
('Bom Jesus de Goias', 9),
('Bonfinopolis', 9),
('Bonopolis', 9),
('Brasilia', 9),
('Brazabrantes', 9),
('Britania', 9),
('Buriti Alegre', 9),
('Buriti de Goias', 9),
('Buritinopolis', 9),
('Cabeceiras', 9),
('Cachoeira Alta', 9),
('Cachoeira Dourada', 9),
('Cachoeira de Goias', 9),
('Cacu', 9),
('Caiaponia', 9),
('Caldas Novas', 9),
('Caldazinha', 9),
('Campestre de Goias', 9),
('Campinacu', 9),
('Campinorte', 9),
('Campo Alegre de Goias', 9),
('Campos Belos', 9),
('Campos Verdes', 9),
('Carmo do Rio Verde', 9),
('Castelandia', 9),
('Catalao', 9),
('Caturai', 9),
('Cavalcante', 9),
('Ceres', 9),
('Cezarina', 9),
('Chapadao do Ceu', 9),
('Cidade Ocidental', 9),
('Cocalzinho de Goias', 9),
('Colinas do Sul', 9),
('Corrego do Ouro', 9),
('Corumba de Goias', 9),
('Corumbaiba', 9),
('Cristalina', 9),
('Cristianopolis', 9),
('Crixas', 9),
('Crominia', 9),
('Cumari', 9),
('Damianopolis', 9),
('Damolandia', 9),
('Davinopolis', 9),
('Diorama', 9),
('Divinopolis de Goias', 9),
('Doverlandia', 9),
('Edealina', 9),
('Edeia', 9),
('Estrela do Norte', 9),
('Faina', 9),
('Fazenda Nova', 9),
('Firminopolis', 9),
('Flores de Goias', 9),
('Formosa', 9),
('Formoso', 9),
('Goianapolis', 9),
('Goiandira', 9),
('Goianesia', 9),
('Goiania', 9),
('Goianira', 9),
('Goias', 9),
('Goiatuba', 9),
('Gouvelandia', 9),
('Guapo', 9),
('Guaraita', 9),
('Guarani de Goias', 9),
('Guarinos', 9),
('Heitorai', 9),
('Hidrolandia', 9),
('Hidrolina', 9),
('Iaciara', 9),
('Inaciolandia', 9),
('Indiara', 9),
('Inhumas', 9),
('Ipameri', 9),
('Ipora', 9),
('Israelandia', 9),
('Itaberai', 9),
('Itaguari', 9),
('Itaguaru', 9),
('Itaja', 9),
('Itapaci', 9),
('Itapirapua', 9),
('Itapuranga', 9),
('Itaruma', 9),
('Itaucu', 9),
('Itumbiara', 9),
('Ivolandia', 9),
('Jandaia', 9),
('Jaragua', 9),
('Jatai', 9),
('Jaupaci', 9),
('Jesupolis', 9),
('Joviania', 9),
('Jussara', 9),
('Leopoldo de Bulhoes', 9),
('Luziania', 9),
('Mairipotaba', 9),
('Mambai', 9),
('Mara Rosa', 9),
('Marzagao', 9),
('Matrincha', 9),
('Maurilandia', 9),
('Mimoso de Goias', 9),
('Minacu', 9),
('Mineiros', 9),
('Moipora', 9),
('Monte Alegre de Goias', 9),
('Montes Claros de Goias', 9),
('Montividiu do Norte', 9),
('Montividiu', 9),
('Morrinhos', 9),
('Morro Agudo de Goias', 9),
('Mossamedes', 9),
('Mozarlandia', 9),
('Mundo Novo', 9),
('Mutunopolis', 9),
('Nazario', 9),
('Neropolis', 9),
('Niquelandia', 9),
('Nova America', 9),
('Nova Aurora', 9),
('Nova Crixas', 9),
('Nova Gloria', 9),
('Nova Iguacu de Goias', 9),
('Nova Roma', 9),
('Nova Veneza', 9),
('Novo Brasil', 9),
('Novo Gama', 9),
('Novo Planalto', 9),
('Orizona', 9),
('Ouro Verde de Goias', 9),
('Ouvidor', 9),
('Padre Bernardo', 9),
('Palestina de Goias', 9),
('Palmeiras de Goias', 9),
('Palmelo', 9),
('Palminopolis', 9),
('Panama', 9),
('Paranaiguara', 9),
('Parauna', 9),
('Perolandia', 9),
('Petrolina de Goias', 9),
('Pilar de Goias', 9),
('Piracanjuba', 9),
('Piranhas', 9),
('Pirenopolis', 9),
('Pires do Rio', 9),
('Planaltina', 9),
('Pontalina', 9),
('Porangatu', 9),
('Porteirao', 9),
('Portelandia', 9),
('Posse', 9),
('Professor Jamil', 9),
('Quirinopolis', 9),
('Rialma', 9),
('Rianapolis', 9),
('Rio Quente', 9),
('Rio Verde', 9),
('Rubiataba', 9),
('Sanclerlandia', 9),
('Santa Barbara de Goias', 9),
('Santa Cruz de Goias', 9),
('Santa Fe de Goias', 9),
('Santa Helena de Goias', 9),
('Santa Isabel', 9),
('Santa Rita do Araguaia', 9),
('Santa Rita do Novo Destino', 9),
('Santa Rosa de Goias', 9),
('Santa Tereza de Goias', 9),
('Santa Terezinha de Goias', 9),
('Santo Antonio da Barra', 9),
('Santo Antonio de Goias', 9),
('Santo Antonio do Descoberto', 9),
('Sao Domingos', 9),
('Sao Francisco de Goias', 9),
('Sao Joao d\'Alianca', 9),
('Sao Joao da Parauna', 9),
('Sao Luis de Montes Belos', 9),
('Sao Luiz do Norte', 9),
('Sao Miguel do Araguaia', 9),
('Sao Miguel do Passa Quatro', 9),
('Sao Patricio', 9),
('Sao Simao', 9),
('Senador Canedo', 9),
('Serranopolis', 9),
('Silvania', 9),
('Simolandia', 9),
('Sitio d\'Abadia', 9),
('Taquaral de Goias', 9),
('Teresina de Goias', 9),
('Terezopolis de Goias', 9),
('Tres Ranchos', 9),
('Trindade', 9),
('Trombas', 9),
('Turvania', 9),
('Turvelandia', 9),
('Uirapuru', 9),
('Uruacu', 9),
('Uruana', 9),
('Urutai', 9),
('Valparaiso de Goias', 9),
('Varjao', 9),
('Vianopolis', 9),
('Vicentinopolis', 9),
('Vila Boa', 9),
('Vila Propicio', 9);
